// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: ethernet_service/v26/ethernet_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EthernetService_ListEthernetInterfaces_FullMethodName    = "/api.gravity.v26.EthernetService/ListEthernetInterfaces"
	EthernetService_IsEthernetConnected_FullMethodName       = "/api.gravity.v26.EthernetService/IsEthernetConnected"
	EthernetService_GetEthernetLinkProperties_FullMethodName = "/api.gravity.v26.EthernetService/GetEthernetLinkProperties"
	EthernetService_SetEthernetConfig_FullMethodName         = "/api.gravity.v26.EthernetService/SetEthernetConfig"
	EthernetService_EnableEthernet_FullMethodName            = "/api.gravity.v26.EthernetService/EnableEthernet"
	EthernetService_DisableEthernet_FullMethodName           = "/api.gravity.v26.EthernetService/DisableEthernet"
)

// EthernetServiceClient is the client API for EthernetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EthernetService definition
type EthernetServiceClient interface {
	// Lists all Ethernet interfaces and their states
	ListEthernetInterfaces(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*EthernetInterfacesResponse, error)
	// Checks if an Ethernet interface is connected
	IsEthernetConnected(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Returns link properties of an interface
	GetEthernetLinkProperties(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*EthernetLinkPropertiesResponse, error)
	// Configures static IP or DHCP for an interface
	SetEthernetConfig(ctx context.Context, in *EthernetConfig, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Enables the Ethernet interface
	EnableEthernet(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Disables the Ethernet interface
	DisableEthernet(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
}

type ethernetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEthernetServiceClient(cc grpc.ClientConnInterface) EthernetServiceClient {
	return &ethernetServiceClient{cc}
}

func (c *ethernetServiceClient) ListEthernetInterfaces(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*EthernetInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EthernetInterfacesResponse)
	err := c.cc.Invoke(ctx, EthernetService_ListEthernetInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethernetServiceClient) IsEthernetConnected(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, EthernetService_IsEthernetConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethernetServiceClient) GetEthernetLinkProperties(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*EthernetLinkPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EthernetLinkPropertiesResponse)
	err := c.cc.Invoke(ctx, EthernetService_GetEthernetLinkProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethernetServiceClient) SetEthernetConfig(ctx context.Context, in *EthernetConfig, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, EthernetService_SetEthernetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethernetServiceClient) EnableEthernet(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, EthernetService_EnableEthernet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethernetServiceClient) DisableEthernet(ctx context.Context, in *InterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, EthernetService_DisableEthernet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthernetServiceServer is the server API for EthernetService service.
// All implementations must embed UnimplementedEthernetServiceServer
// for forward compatibility.
//
// EthernetService definition
type EthernetServiceServer interface {
	// Lists all Ethernet interfaces and their states
	ListEthernetInterfaces(context.Context, *common.Empty) (*EthernetInterfacesResponse, error)
	// Checks if an Ethernet interface is connected
	IsEthernetConnected(context.Context, *InterfaceRequest) (*common.BooleanResponse, error)
	// Returns link properties of an interface
	GetEthernetLinkProperties(context.Context, *InterfaceRequest) (*EthernetLinkPropertiesResponse, error)
	// Configures static IP or DHCP for an interface
	SetEthernetConfig(context.Context, *EthernetConfig) (*common.BooleanResponse, error)
	// Enables the Ethernet interface
	EnableEthernet(context.Context, *InterfaceRequest) (*common.BooleanResponse, error)
	// Disables the Ethernet interface
	DisableEthernet(context.Context, *InterfaceRequest) (*common.BooleanResponse, error)
	mustEmbedUnimplementedEthernetServiceServer()
}

// UnimplementedEthernetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEthernetServiceServer struct{}

func (UnimplementedEthernetServiceServer) ListEthernetInterfaces(context.Context, *common.Empty) (*EthernetInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEthernetInterfaces not implemented")
}
func (UnimplementedEthernetServiceServer) IsEthernetConnected(context.Context, *InterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsEthernetConnected not implemented")
}
func (UnimplementedEthernetServiceServer) GetEthernetLinkProperties(context.Context, *InterfaceRequest) (*EthernetLinkPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEthernetLinkProperties not implemented")
}
func (UnimplementedEthernetServiceServer) SetEthernetConfig(context.Context, *EthernetConfig) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEthernetConfig not implemented")
}
func (UnimplementedEthernetServiceServer) EnableEthernet(context.Context, *InterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableEthernet not implemented")
}
func (UnimplementedEthernetServiceServer) DisableEthernet(context.Context, *InterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableEthernet not implemented")
}
func (UnimplementedEthernetServiceServer) mustEmbedUnimplementedEthernetServiceServer() {}
func (UnimplementedEthernetServiceServer) testEmbeddedByValue()                         {}

// UnsafeEthernetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EthernetServiceServer will
// result in compilation errors.
type UnsafeEthernetServiceServer interface {
	mustEmbedUnimplementedEthernetServiceServer()
}

func RegisterEthernetServiceServer(s grpc.ServiceRegistrar, srv EthernetServiceServer) {
	// If the following call panics, it indicates UnimplementedEthernetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EthernetService_ServiceDesc, srv)
}

func _EthernetService_ListEthernetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).ListEthernetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_ListEthernetInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).ListEthernetInterfaces(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthernetService_IsEthernetConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).IsEthernetConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_IsEthernetConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).IsEthernetConnected(ctx, req.(*InterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthernetService_GetEthernetLinkProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).GetEthernetLinkProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_GetEthernetLinkProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).GetEthernetLinkProperties(ctx, req.(*InterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthernetService_SetEthernetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EthernetConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).SetEthernetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_SetEthernetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).SetEthernetConfig(ctx, req.(*EthernetConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthernetService_EnableEthernet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).EnableEthernet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_EnableEthernet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).EnableEthernet(ctx, req.(*InterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthernetService_DisableEthernet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthernetServiceServer).DisableEthernet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthernetService_DisableEthernet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthernetServiceServer).DisableEthernet(ctx, req.(*InterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EthernetService_ServiceDesc is the grpc.ServiceDesc for EthernetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EthernetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.EthernetService",
	HandlerType: (*EthernetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEthernetInterfaces",
			Handler:    _EthernetService_ListEthernetInterfaces_Handler,
		},
		{
			MethodName: "IsEthernetConnected",
			Handler:    _EthernetService_IsEthernetConnected_Handler,
		},
		{
			MethodName: "GetEthernetLinkProperties",
			Handler:    _EthernetService_GetEthernetLinkProperties_Handler,
		},
		{
			MethodName: "SetEthernetConfig",
			Handler:    _EthernetService_SetEthernetConfig_Handler,
		},
		{
			MethodName: "EnableEthernet",
			Handler:    _EthernetService_EnableEthernet_Handler,
		},
		{
			MethodName: "DisableEthernet",
			Handler:    _EthernetService_DisableEthernet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ethernet_service/v26/ethernet_service.proto",
}
