// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: ai_service/v26/ai_service.proto

package v26

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_LoadModel_FullMethodName          = "/api.gravity.v26.AiService/LoadModel"
	AiService_UploadAndLoadModel_FullMethodName = "/api.gravity.v26.AiService/UploadAndLoadModel"
	AiService_UnloadModel_FullMethodName        = "/api.gravity.v26.AiService/UnloadModel"
	AiService_ListModels_FullMethodName         = "/api.gravity.v26.AiService/ListModels"
	AiService_IsModelLoaded_FullMethodName      = "/api.gravity.v26.AiService/IsModelLoaded"
	AiService_Infer_FullMethodName              = "/api.gravity.v26.AiService/Infer"
	AiService_StreamInfer_FullMethodName        = "/api.gravity.v26.AiService/StreamInfer"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiServiceClient interface {
	// Load a model that already exists on the device filesystem.
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// Upload a model file from the client in chunks, then load it.
	// First chunk must contain UploadModelChunk.meta; subsequent chunks contain data.
	// The server streams back a single LoadModelResponse when done.
	UploadAndLoadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadModelChunk, LoadModelResponse], error)
	// Unload a model
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// List loaded models
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Check whether a specific model is currently loaded.
	// Returns loaded=true and the tensor schema if it is, loaded=false otherwise.
	// Cheaper than ListModels when you only need to check one model.
	IsModelLoaded(ctx context.Context, in *IsModelLoadedRequest, opts ...grpc.CallOption) (*IsModelLoadedResponse, error)
	// Run inference
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
	// Stream inference (bidi: send frames, receive results)
	StreamInfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferRequest, InferResponse], error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, AiService_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) UploadAndLoadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadModelChunk, LoadModelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiService_ServiceDesc.Streams[0], AiService_UploadAndLoadModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadModelChunk, LoadModelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_UploadAndLoadModelClient = grpc.ClientStreamingClient[UploadModelChunk, LoadModelResponse]

func (c *aiServiceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, AiService_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, AiService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) IsModelLoaded(ctx context.Context, in *IsModelLoadedRequest, opts ...grpc.CallOption) (*IsModelLoadedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsModelLoadedResponse)
	err := c.cc.Invoke(ctx, AiService_IsModelLoaded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, AiService_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) StreamInfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferRequest, InferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiService_ServiceDesc.Streams[1], AiService_StreamInfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferRequest, InferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_StreamInferClient = grpc.BidiStreamingClient[InferRequest, InferResponse]

// AiServiceServer is the server API for AiService service.
// All implementations must embed UnimplementedAiServiceServer
// for forward compatibility.
type AiServiceServer interface {
	// Load a model that already exists on the device filesystem.
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// Upload a model file from the client in chunks, then load it.
	// First chunk must contain UploadModelChunk.meta; subsequent chunks contain data.
	// The server streams back a single LoadModelResponse when done.
	UploadAndLoadModel(grpc.ClientStreamingServer[UploadModelChunk, LoadModelResponse]) error
	// Unload a model
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// List loaded models
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Check whether a specific model is currently loaded.
	// Returns loaded=true and the tensor schema if it is, loaded=false otherwise.
	// Cheaper than ListModels when you only need to check one model.
	IsModelLoaded(context.Context, *IsModelLoadedRequest) (*IsModelLoadedResponse, error)
	// Run inference
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	// Stream inference (bidi: send frames, receive results)
	StreamInfer(grpc.BidiStreamingServer[InferRequest, InferResponse]) error
	mustEmbedUnimplementedAiServiceServer()
}

// UnimplementedAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedAiServiceServer) UploadAndLoadModel(grpc.ClientStreamingServer[UploadModelChunk, LoadModelResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadAndLoadModel not implemented")
}
func (UnimplementedAiServiceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedAiServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAiServiceServer) IsModelLoaded(context.Context, *IsModelLoadedRequest) (*IsModelLoadedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsModelLoaded not implemented")
}
func (UnimplementedAiServiceServer) Infer(context.Context, *InferRequest) (*InferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedAiServiceServer) StreamInfer(grpc.BidiStreamingServer[InferRequest, InferResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamInfer not implemented")
}
func (UnimplementedAiServiceServer) mustEmbedUnimplementedAiServiceServer() {}
func (UnimplementedAiServiceServer) testEmbeddedByValue()                   {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call panics, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_UploadAndLoadModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AiServiceServer).UploadAndLoadModel(&grpc.GenericServerStream[UploadModelChunk, LoadModelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_UploadAndLoadModelServer = grpc.ClientStreamingServer[UploadModelChunk, LoadModelResponse]

func _AiService_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_IsModelLoaded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsModelLoadedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).IsModelLoaded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_IsModelLoaded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).IsModelLoaded(ctx, req.(*IsModelLoadedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_StreamInfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AiServiceServer).StreamInfer(&grpc.GenericServerStream[InferRequest, InferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_StreamInferServer = grpc.BidiStreamingServer[InferRequest, InferResponse]

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadModel",
			Handler:    _AiService_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _AiService_UnloadModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AiService_ListModels_Handler,
		},
		{
			MethodName: "IsModelLoaded",
			Handler:    _AiService_IsModelLoaded_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _AiService_Infer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadAndLoadModel",
			Handler:       _AiService_UploadAndLoadModel_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamInfer",
			Handler:       _AiService_StreamInfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ai_service/v26/ai_service.proto",
}
