// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: ai_service/v26/ai_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelBackend int32

const (
	ModelBackend_MODEL_BACKEND_UNSPECIFIED ModelBackend = 0
	ModelBackend_ONNX                      ModelBackend = 1
	ModelBackend_TFLITE                    ModelBackend = 2
)

// Enum value maps for ModelBackend.
var (
	ModelBackend_name = map[int32]string{
		0: "MODEL_BACKEND_UNSPECIFIED",
		1: "ONNX",
		2: "TFLITE",
	}
	ModelBackend_value = map[string]int32{
		"MODEL_BACKEND_UNSPECIFIED": 0,
		"ONNX":                      1,
		"TFLITE":                    2,
	}
)

func (x ModelBackend) Enum() *ModelBackend {
	p := new(ModelBackend)
	*p = x
	return p
}

func (x ModelBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_v26_ai_service_proto_enumTypes[0].Descriptor()
}

func (ModelBackend) Type() protoreflect.EnumType {
	return &file_ai_service_v26_ai_service_proto_enumTypes[0]
}

func (x ModelBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelBackend.Descriptor instead.
func (ModelBackend) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{0}
}

// ExecutionMode controls which compute path the backend uses.
type ExecutionMode int32

const (
	ExecutionMode_EXEC_CPU          ExecutionMode = 0 // Default: single/multi core CPU
	ExecutionMode_EXEC_GPU          ExecutionMode = 1 // GPU / NPU delegate
	ExecutionMode_EXEC_HIGH_THREADS ExecutionMode = 2 // CPU with maximum thread count
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXEC_CPU",
		1: "EXEC_GPU",
		2: "EXEC_HIGH_THREADS",
	}
	ExecutionMode_value = map[string]int32{
		"EXEC_CPU":          0,
		"EXEC_GPU":          1,
		"EXEC_HIGH_THREADS": 2,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_v26_ai_service_proto_enumTypes[1].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_ai_service_v26_ai_service_proto_enumTypes[1]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{1}
}

// TensorDataType describes how raw bytes in InferRequest/InferResponse are encoded.
type TensorDataType int32

const (
	TensorDataType_TENSOR_FLOAT32 TensorDataType = 0 // 4-byte little-endian IEEE 754, normalised [0, 1]
	TensorDataType_TENSOR_UINT8   TensorDataType = 1 // 1-byte unsigned integer [0, 255]
	TensorDataType_TENSOR_INT32   TensorDataType = 2 // 4-byte little-endian signed integer
	TensorDataType_TENSOR_INT64   TensorDataType = 3 // 8-byte little-endian signed integer
)

// Enum value maps for TensorDataType.
var (
	TensorDataType_name = map[int32]string{
		0: "TENSOR_FLOAT32",
		1: "TENSOR_UINT8",
		2: "TENSOR_INT32",
		3: "TENSOR_INT64",
	}
	TensorDataType_value = map[string]int32{
		"TENSOR_FLOAT32": 0,
		"TENSOR_UINT8":   1,
		"TENSOR_INT32":   2,
		"TENSOR_INT64":   3,
	}
)

func (x TensorDataType) Enum() *TensorDataType {
	p := new(TensorDataType)
	*p = x
	return p
}

func (x TensorDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TensorDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_v26_ai_service_proto_enumTypes[2].Descriptor()
}

func (TensorDataType) Type() protoreflect.EnumType {
	return &file_ai_service_v26_ai_service_proto_enumTypes[2]
}

func (x TensorDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TensorDataType.Descriptor instead.
func (TensorDataType) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{2}
}

type LoadModelRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Path in local filesystem (or mounted storage)
	ModelPath string `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	// Backend type: ONNX / TFLITE
	Backend ModelBackend `protobuf:"varint,3,opt,name=backend,proto3,enum=api.gravity.v26.ModelBackend" json:"backend,omitempty"`
	// Optional: versioning
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Optional generic config (deprecated in favour of execution field below)
	Options map[string]string `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Execution preference for inference (default = CPU)
	Execution     ExecutionMode `protobuf:"varint,6,opt,name=execution,proto3,enum=api.gravity.v26.ExecutionMode" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *LoadModelRequest) GetBackend() ModelBackend {
	if x != nil {
		return x.Backend
	}
	return ModelBackend_MODEL_BACKEND_UNSPECIFIED
}

func (x *LoadModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LoadModelRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *LoadModelRequest) GetExecution() ExecutionMode {
	if x != nil {
		return x.Execution
	}
	return ExecutionMode_EXEC_CPU
}

type LoadModelResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   *common.ErrorInfo      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Input and output tensor schema reported by the backend after loading.
	// Clients should use these to know how to pack input_data in InferRequest.
	Inputs  []*TensorInfo `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs []*TensorInfo `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// True when the model was already loaded in the backend and the upload was
	// skipped. The schema (inputs/outputs) is still populated in this case.
	SkippedUpload bool `protobuf:"varint,6,opt,name=skipped_upload,json=skippedUpload,proto3" json:"skipped_upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoadModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *LoadModelResponse) GetInputs() []*TensorInfo {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *LoadModelResponse) GetOutputs() []*TensorInfo {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *LoadModelResponse) GetSkippedUpload() bool {
	if x != nil {
		return x.SkippedUpload
	}
	return false
}

// UploadModelChunk is a single message in the UploadAndLoadModel stream.
// The first chunk must carry meta; all others carry raw file bytes.
type UploadModelChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadModelChunk_Meta
	//	*UploadModelChunk_Data
	Payload       isUploadModelChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelChunk) Reset() {
	*x = UploadModelChunk{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelChunk) ProtoMessage() {}

func (x *UploadModelChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelChunk.ProtoReflect.Descriptor instead.
func (*UploadModelChunk) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadModelChunk) GetPayload() isUploadModelChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadModelChunk) GetMeta() *UploadModelMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadModelChunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadModelChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadModelChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadModelChunk_Payload interface {
	isUploadModelChunk_Payload()
}

type UploadModelChunk_Meta struct {
	Meta *UploadModelMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadModelChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadModelChunk_Meta) isUploadModelChunk_Payload() {}

func (*UploadModelChunk_Data) isUploadModelChunk_Payload() {}

// UploadModelMeta is sent as the first chunk of UploadAndLoadModel.
type UploadModelMeta struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ModelId   string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Backend   ModelBackend           `protobuf:"varint,2,opt,name=backend,proto3,enum=api.gravity.v26.ModelBackend" json:"backend,omitempty"`
	Execution ExecutionMode          `protobuf:"varint,3,opt,name=execution,proto3,enum=api.gravity.v26.ExecutionMode" json:"execution,omitempty"`
	Version   string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Expected total byte size of the model file (informational; used for progress).
	TotalBytes int64 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Original filename (used to determine file extension, e.g. "yolo.tflite").
	Filename      string `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadModelMeta) Reset() {
	*x = UploadModelMeta{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadModelMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelMeta) ProtoMessage() {}

func (x *UploadModelMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelMeta.ProtoReflect.Descriptor instead.
func (*UploadModelMeta) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadModelMeta) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UploadModelMeta) GetBackend() ModelBackend {
	if x != nil {
		return x.Backend
	}
	return ModelBackend_MODEL_BACKEND_UNSPECIFIED
}

func (x *UploadModelMeta) GetExecution() ExecutionMode {
	if x != nil {
		return x.Execution
	}
	return ExecutionMode_EXEC_CPU
}

func (x *UploadModelMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadModelMeta) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadModelMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *UnloadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadModelResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{6}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Backend       ModelBackend           `protobuf:"varint,3,opt,name=backend,proto3,enum=api.gravity.v26.ModelBackend" json:"backend,omitempty"`
	LoadedAtUnix  int64                  `protobuf:"varint,4,opt,name=loaded_at_unix,json=loadedAtUnix,proto3" json:"loaded_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ModelInfo) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfo) GetBackend() ModelBackend {
	if x != nil {
		return x.Backend
	}
	return ModelBackend_MODEL_BACKEND_UNSPECIFIED
}

func (x *ModelInfo) GetLoadedAtUnix() int64 {
	if x != nil {
		return x.LoadedAtUnix
	}
	return 0
}

type IsModelLoadedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModelLoadedRequest) Reset() {
	*x = IsModelLoadedRequest{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModelLoadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModelLoadedRequest) ProtoMessage() {}

func (x *IsModelLoadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModelLoadedRequest.ProtoReflect.Descriptor instead.
func (*IsModelLoadedRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *IsModelLoadedRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type IsModelLoadedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the model is currently loaded and ready for inference.
	Loaded bool `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	// Tensor schema — populated when loaded=true so the caller can start
	// inference immediately without an extra LoadModel call.
	Inputs        []*TensorInfo `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TensorInfo `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModelLoadedResponse) Reset() {
	*x = IsModelLoadedResponse{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModelLoadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModelLoadedResponse) ProtoMessage() {}

func (x *IsModelLoadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModelLoadedResponse.ProtoReflect.Descriptor instead.
func (*IsModelLoadedResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *IsModelLoadedResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *IsModelLoadedResponse) GetInputs() []*TensorInfo {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *IsModelLoadedResponse) GetOutputs() []*TensorInfo {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type InferRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Raw tensor input bytes.
	// Encoding is determined by input_dtype:
	//
	//	FLOAT32 (default) — little-endian IEEE 754 floats, normalised [0, 1]
	//	UINT8             — raw byte values [0, 255]
	InputData []byte `protobuf:"bytes,2,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	// Shape of the input tensor, e.g. [1, 640, 640, 3].
	// If omitted, the shape reported by LoadModel (TensorInfo) is used.
	InputShape []int32 `protobuf:"varint,3,rep,packed,name=input_shape,json=inputShape,proto3" json:"input_shape,omitempty"`
	// Optional: named inputs for multi-input models (map[tensor_name] -> raw bytes).
	// Each value is encoded according to input_dtype.
	NamedInputs map[string][]byte `protobuf:"bytes,4,rep,name=named_inputs,json=namedInputs,proto3" json:"named_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional runtime parameters (pass-through to backend)
	Params map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Dtype of input_data / named_inputs bytes.
	// Defaults to FLOAT32 if omitted; must match what the model expects.
	// Use LoadModelResponse.inputs[0].dtype to determine the correct value.
	InputDtype    TensorDataType `protobuf:"varint,6,opt,name=input_dtype,json=inputDtype,proto3,enum=api.gravity.v26.TensorDataType" json:"input_dtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *InferRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *InferRequest) GetInputShape() []int32 {
	if x != nil {
		return x.InputShape
	}
	return nil
}

func (x *InferRequest) GetNamedInputs() map[string][]byte {
	if x != nil {
		return x.NamedInputs
	}
	return nil
}

func (x *InferRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *InferRequest) GetInputDtype() TensorDataType {
	if x != nil {
		return x.InputDtype
	}
	return TensorDataType_TENSOR_FLOAT32
}

type InferResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// First output tensor as raw bytes (little-endian float32 or uint8)
	OutputData []byte `protobuf:"bytes,3,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	// Shape of output_data
	OutputShape []int32 `protobuf:"varint,4,rep,packed,name=output_shape,json=outputShape,proto3" json:"output_shape,omitempty"`
	// All outputs by tensor name (same encoding as output_data)
	NamedOutputs map[string][]byte `protobuf:"bytes,5,rep,name=named_outputs,json=namedOutputs,proto3" json:"named_outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Inference wall time measured at the backend
	LatencyUs     int64 `protobuf:"varint,6,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *InferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InferResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InferResponse) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *InferResponse) GetOutputShape() []int32 {
	if x != nil {
		return x.OutputShape
	}
	return nil
}

func (x *InferResponse) GetNamedOutputs() map[string][]byte {
	if x != nil {
		return x.NamedOutputs
	}
	return nil
}

func (x *InferResponse) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

// TensorInfo describes a single input or output tensor of a loaded model.
type TensorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dtype         TensorDataType         `protobuf:"varint,2,opt,name=dtype,proto3,enum=api.gravity.v26.TensorDataType" json:"dtype,omitempty"`
	Shape         []int32                `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorInfo) Reset() {
	*x = TensorInfo{}
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorInfo) ProtoMessage() {}

func (x *TensorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_v26_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorInfo.ProtoReflect.Descriptor instead.
func (*TensorInfo) Descriptor() ([]byte, []int) {
	return file_ai_service_v26_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *TensorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TensorInfo) GetDtype() TensorDataType {
	if x != nil {
		return x.Dtype
	}
	return TensorDataType_TENSOR_FLOAT32
}

func (x *TensorInfo) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

var File_ai_service_v26_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_v26_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x1fai_service/v26/ai_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"\xe3\x02\n" +
	"\x10LoadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x127\n" +
	"\abackend\x18\x03 \x01(\x0e2\x1d.api.gravity.v26.ModelBackendR\abackend\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12H\n" +
	"\aoptions\x18\x05 \x03(\v2..api.gravity.v26.LoadModelRequest.OptionsEntryR\aoptions\x12<\n" +
	"\texecution\x18\x06 \x01(\x0e2\x1e.api.gravity.v26.ExecutionModeR\texecution\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x11LoadModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\x123\n" +
	"\x06inputs\x18\x04 \x03(\v2\x1b.api.gravity.v26.TensorInfoR\x06inputs\x125\n" +
	"\aoutputs\x18\x05 \x03(\v2\x1b.api.gravity.v26.TensorInfoR\aoutputs\x12%\n" +
	"\x0eskipped_upload\x18\x06 \x01(\bR\rskippedUpload\"k\n" +
	"\x10UploadModelChunk\x126\n" +
	"\x04meta\x18\x01 \x01(\v2 .api.gravity.v26.UploadModelMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\xfa\x01\n" +
	"\x0fUploadModelMeta\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x127\n" +
	"\abackend\x18\x02 \x01(\x0e2\x1d.api.gravity.v26.ModelBackendR\abackend\x12<\n" +
	"\texecution\x18\x03 \x01(\x0e2\x1e.api.gravity.v26.ExecutionModeR\texecution\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\"/\n" +
	"\x12UnloadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"c\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\x13\n" +
	"\x11ListModelsRequest\"H\n" +
	"\x12ListModelsResponse\x122\n" +
	"\x06models\x18\x01 \x03(\v2\x1a.api.gravity.v26.ModelInfoR\x06models\"\x9f\x01\n" +
	"\tModelInfo\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x127\n" +
	"\abackend\x18\x03 \x01(\x0e2\x1d.api.gravity.v26.ModelBackendR\abackend\x12$\n" +
	"\x0eloaded_at_unix\x18\x04 \x01(\x03R\floadedAtUnix\"1\n" +
	"\x14IsModelLoadedRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\x9b\x01\n" +
	"\x15IsModelLoadedResponse\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x123\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1b.api.gravity.v26.TensorInfoR\x06inputs\x125\n" +
	"\aoutputs\x18\x03 \x03(\v2\x1b.api.gravity.v26.TensorInfoR\aoutputs\"\xbc\x03\n" +
	"\fInferRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"input_data\x18\x02 \x01(\fR\tinputData\x12\x1f\n" +
	"\vinput_shape\x18\x03 \x03(\x05R\n" +
	"inputShape\x12Q\n" +
	"\fnamed_inputs\x18\x04 \x03(\v2..api.gravity.v26.InferRequest.NamedInputsEntryR\vnamedInputs\x12A\n" +
	"\x06params\x18\x05 \x03(\v2).api.gravity.v26.InferRequest.ParamsEntryR\x06params\x12@\n" +
	"\vinput_dtype\x18\x06 \x01(\x0e2\x1f.api.gravity.v26.TensorDataTypeR\n" +
	"inputDtype\x1a>\n" +
	"\x10NamedInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x02\n" +
	"\rInferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\x12\x1f\n" +
	"\voutput_data\x18\x03 \x01(\fR\n" +
	"outputData\x12!\n" +
	"\foutput_shape\x18\x04 \x03(\x05R\voutputShape\x12U\n" +
	"\rnamed_outputs\x18\x05 \x03(\v20.api.gravity.v26.InferResponse.NamedOutputsEntryR\fnamedOutputs\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x06 \x01(\x03R\tlatencyUs\x1a?\n" +
	"\x11NamedOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"m\n" +
	"\n" +
	"TensorInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x05dtype\x18\x02 \x01(\x0e2\x1f.api.gravity.v26.TensorDataTypeR\x05dtype\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\x05R\x05shape*C\n" +
	"\fModelBackend\x12\x1d\n" +
	"\x19MODEL_BACKEND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04ONNX\x10\x01\x12\n" +
	"\n" +
	"\x06TFLITE\x10\x02*B\n" +
	"\rExecutionMode\x12\f\n" +
	"\bEXEC_CPU\x10\x00\x12\f\n" +
	"\bEXEC_GPU\x10\x01\x12\x15\n" +
	"\x11EXEC_HIGH_THREADS\x10\x02*Z\n" +
	"\x0eTensorDataType\x12\x12\n" +
	"\x0eTENSOR_FLOAT32\x10\x00\x12\x10\n" +
	"\fTENSOR_UINT8\x10\x01\x12\x10\n" +
	"\fTENSOR_INT32\x10\x02\x12\x10\n" +
	"\fTENSOR_INT64\x10\x032\xe9\x04\n" +
	"\tAiService\x12R\n" +
	"\tLoadModel\x12!.api.gravity.v26.LoadModelRequest\x1a\".api.gravity.v26.LoadModelResponse\x12]\n" +
	"\x12UploadAndLoadModel\x12!.api.gravity.v26.UploadModelChunk\x1a\".api.gravity.v26.LoadModelResponse(\x01\x12X\n" +
	"\vUnloadModel\x12#.api.gravity.v26.UnloadModelRequest\x1a$.api.gravity.v26.UnloadModelResponse\x12U\n" +
	"\n" +
	"ListModels\x12\".api.gravity.v26.ListModelsRequest\x1a#.api.gravity.v26.ListModelsResponse\x12^\n" +
	"\rIsModelLoaded\x12%.api.gravity.v26.IsModelLoadedRequest\x1a&.api.gravity.v26.IsModelLoadedResponse\x12F\n" +
	"\x05Infer\x12\x1d.api.gravity.v26.InferRequest\x1a\x1e.api.gravity.v26.InferResponse\x12P\n" +
	"\vStreamInfer\x12\x1d.api.gravity.v26.InferRequest\x1a\x1e.api.gravity.v26.InferResponse(\x010\x01b\x06proto3"

var (
	file_ai_service_v26_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_v26_ai_service_proto_rawDescData []byte
)

func file_ai_service_v26_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_v26_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_v26_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_v26_ai_service_proto_rawDesc), len(file_ai_service_v26_ai_service_proto_rawDesc)))
	})
	return file_ai_service_v26_ai_service_proto_rawDescData
}

var file_ai_service_v26_ai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ai_service_v26_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ai_service_v26_ai_service_proto_goTypes = []any{
	(ModelBackend)(0),             // 0: api.gravity.v26.ModelBackend
	(ExecutionMode)(0),            // 1: api.gravity.v26.ExecutionMode
	(TensorDataType)(0),           // 2: api.gravity.v26.TensorDataType
	(*LoadModelRequest)(nil),      // 3: api.gravity.v26.LoadModelRequest
	(*LoadModelResponse)(nil),     // 4: api.gravity.v26.LoadModelResponse
	(*UploadModelChunk)(nil),      // 5: api.gravity.v26.UploadModelChunk
	(*UploadModelMeta)(nil),       // 6: api.gravity.v26.UploadModelMeta
	(*UnloadModelRequest)(nil),    // 7: api.gravity.v26.UnloadModelRequest
	(*UnloadModelResponse)(nil),   // 8: api.gravity.v26.UnloadModelResponse
	(*ListModelsRequest)(nil),     // 9: api.gravity.v26.ListModelsRequest
	(*ListModelsResponse)(nil),    // 10: api.gravity.v26.ListModelsResponse
	(*ModelInfo)(nil),             // 11: api.gravity.v26.ModelInfo
	(*IsModelLoadedRequest)(nil),  // 12: api.gravity.v26.IsModelLoadedRequest
	(*IsModelLoadedResponse)(nil), // 13: api.gravity.v26.IsModelLoadedResponse
	(*InferRequest)(nil),          // 14: api.gravity.v26.InferRequest
	(*InferResponse)(nil),         // 15: api.gravity.v26.InferResponse
	(*TensorInfo)(nil),            // 16: api.gravity.v26.TensorInfo
	nil,                           // 17: api.gravity.v26.LoadModelRequest.OptionsEntry
	nil,                           // 18: api.gravity.v26.InferRequest.NamedInputsEntry
	nil,                           // 19: api.gravity.v26.InferRequest.ParamsEntry
	nil,                           // 20: api.gravity.v26.InferResponse.NamedOutputsEntry
	(*common.ErrorInfo)(nil),      // 21: api.gravity.types.ErrorInfo
}
var file_ai_service_v26_ai_service_proto_depIdxs = []int32{
	0,  // 0: api.gravity.v26.LoadModelRequest.backend:type_name -> api.gravity.v26.ModelBackend
	17, // 1: api.gravity.v26.LoadModelRequest.options:type_name -> api.gravity.v26.LoadModelRequest.OptionsEntry
	1,  // 2: api.gravity.v26.LoadModelRequest.execution:type_name -> api.gravity.v26.ExecutionMode
	21, // 3: api.gravity.v26.LoadModelResponse.error:type_name -> api.gravity.types.ErrorInfo
	16, // 4: api.gravity.v26.LoadModelResponse.inputs:type_name -> api.gravity.v26.TensorInfo
	16, // 5: api.gravity.v26.LoadModelResponse.outputs:type_name -> api.gravity.v26.TensorInfo
	6,  // 6: api.gravity.v26.UploadModelChunk.meta:type_name -> api.gravity.v26.UploadModelMeta
	0,  // 7: api.gravity.v26.UploadModelMeta.backend:type_name -> api.gravity.v26.ModelBackend
	1,  // 8: api.gravity.v26.UploadModelMeta.execution:type_name -> api.gravity.v26.ExecutionMode
	21, // 9: api.gravity.v26.UnloadModelResponse.error:type_name -> api.gravity.types.ErrorInfo
	11, // 10: api.gravity.v26.ListModelsResponse.models:type_name -> api.gravity.v26.ModelInfo
	0,  // 11: api.gravity.v26.ModelInfo.backend:type_name -> api.gravity.v26.ModelBackend
	16, // 12: api.gravity.v26.IsModelLoadedResponse.inputs:type_name -> api.gravity.v26.TensorInfo
	16, // 13: api.gravity.v26.IsModelLoadedResponse.outputs:type_name -> api.gravity.v26.TensorInfo
	18, // 14: api.gravity.v26.InferRequest.named_inputs:type_name -> api.gravity.v26.InferRequest.NamedInputsEntry
	19, // 15: api.gravity.v26.InferRequest.params:type_name -> api.gravity.v26.InferRequest.ParamsEntry
	2,  // 16: api.gravity.v26.InferRequest.input_dtype:type_name -> api.gravity.v26.TensorDataType
	21, // 17: api.gravity.v26.InferResponse.error:type_name -> api.gravity.types.ErrorInfo
	20, // 18: api.gravity.v26.InferResponse.named_outputs:type_name -> api.gravity.v26.InferResponse.NamedOutputsEntry
	2,  // 19: api.gravity.v26.TensorInfo.dtype:type_name -> api.gravity.v26.TensorDataType
	3,  // 20: api.gravity.v26.AiService.LoadModel:input_type -> api.gravity.v26.LoadModelRequest
	5,  // 21: api.gravity.v26.AiService.UploadAndLoadModel:input_type -> api.gravity.v26.UploadModelChunk
	7,  // 22: api.gravity.v26.AiService.UnloadModel:input_type -> api.gravity.v26.UnloadModelRequest
	9,  // 23: api.gravity.v26.AiService.ListModels:input_type -> api.gravity.v26.ListModelsRequest
	12, // 24: api.gravity.v26.AiService.IsModelLoaded:input_type -> api.gravity.v26.IsModelLoadedRequest
	14, // 25: api.gravity.v26.AiService.Infer:input_type -> api.gravity.v26.InferRequest
	14, // 26: api.gravity.v26.AiService.StreamInfer:input_type -> api.gravity.v26.InferRequest
	4,  // 27: api.gravity.v26.AiService.LoadModel:output_type -> api.gravity.v26.LoadModelResponse
	4,  // 28: api.gravity.v26.AiService.UploadAndLoadModel:output_type -> api.gravity.v26.LoadModelResponse
	8,  // 29: api.gravity.v26.AiService.UnloadModel:output_type -> api.gravity.v26.UnloadModelResponse
	10, // 30: api.gravity.v26.AiService.ListModels:output_type -> api.gravity.v26.ListModelsResponse
	13, // 31: api.gravity.v26.AiService.IsModelLoaded:output_type -> api.gravity.v26.IsModelLoadedResponse
	15, // 32: api.gravity.v26.AiService.Infer:output_type -> api.gravity.v26.InferResponse
	15, // 33: api.gravity.v26.AiService.StreamInfer:output_type -> api.gravity.v26.InferResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_ai_service_v26_ai_service_proto_init() }
func file_ai_service_v26_ai_service_proto_init() {
	if File_ai_service_v26_ai_service_proto != nil {
		return
	}
	file_ai_service_v26_ai_service_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadModelChunk_Meta)(nil),
		(*UploadModelChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_v26_ai_service_proto_rawDesc), len(file_ai_service_v26_ai_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_v26_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_v26_ai_service_proto_depIdxs,
		EnumInfos:         file_ai_service_v26_ai_service_proto_enumTypes,
		MessageInfos:      file_ai_service_v26_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_v26_ai_service_proto = out.File
	file_ai_service_v26_ai_service_proto_goTypes = nil
	file_ai_service_v26_ai_service_proto_depIdxs = nil
}
