// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: cellular_service/v26/cellular_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CellularService_ListCellularInterfaces_FullMethodName    = "/api.gravity.v26.CellularService/ListCellularInterfaces"
	CellularService_IsCellularConnected_FullMethodName       = "/api.gravity.v26.CellularService/IsCellularConnected"
	CellularService_GetCellularLinkProperties_FullMethodName = "/api.gravity.v26.CellularService/GetCellularLinkProperties"
	CellularService_SetCellularConfig_FullMethodName         = "/api.gravity.v26.CellularService/SetCellularConfig"
	CellularService_Connect_FullMethodName                   = "/api.gravity.v26.CellularService/Connect"
	CellularService_Disconnect_FullMethodName                = "/api.gravity.v26.CellularService/Disconnect"
	CellularService_SubscribeCellularEvents_FullMethodName   = "/api.gravity.v26.CellularService/SubscribeCellularEvents"
)

// CellularServiceClient is the client API for CellularService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CellularServiceClient interface {
	// Lists all cellular interfaces and their states
	ListCellularInterfaces(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CellularInterfacesResponse, error)
	// Checks if a cellular interface is connected
	IsCellularConnected(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Returns link properties of an interface
	GetCellularLinkProperties(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*CellularLinkPropertiesResponse, error)
	// Configures static IP or DHCP for an interface
	SetCellularConfig(ctx context.Context, in *CellularConfig, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Connects / activates the cellular connection
	Connect(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Disconnects / deactivates the cellular connection
	Disconnect(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Observes modem / network state changes
	SubscribeCellularEvents(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CellularLinkProperties], error)
}

type cellularServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCellularServiceClient(cc grpc.ClientConnInterface) CellularServiceClient {
	return &cellularServiceClient{cc}
}

func (c *cellularServiceClient) ListCellularInterfaces(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CellularInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellularInterfacesResponse)
	err := c.cc.Invoke(ctx, CellularService_ListCellularInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) IsCellularConnected(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, CellularService_IsCellularConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) GetCellularLinkProperties(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*CellularLinkPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellularLinkPropertiesResponse)
	err := c.cc.Invoke(ctx, CellularService_GetCellularLinkProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) SetCellularConfig(ctx context.Context, in *CellularConfig, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, CellularService_SetCellularConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) Connect(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, CellularService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) Disconnect(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, CellularService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellularServiceClient) SubscribeCellularEvents(ctx context.Context, in *CellularInterfaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CellularLinkProperties], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CellularService_ServiceDesc.Streams[0], CellularService_SubscribeCellularEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CellularInterfaceRequest, CellularLinkProperties]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CellularService_SubscribeCellularEventsClient = grpc.ServerStreamingClient[CellularLinkProperties]

// CellularServiceServer is the server API for CellularService service.
// All implementations must embed UnimplementedCellularServiceServer
// for forward compatibility.
type CellularServiceServer interface {
	// Lists all cellular interfaces and their states
	ListCellularInterfaces(context.Context, *common.Empty) (*CellularInterfacesResponse, error)
	// Checks if a cellular interface is connected
	IsCellularConnected(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error)
	// Returns link properties of an interface
	GetCellularLinkProperties(context.Context, *CellularInterfaceRequest) (*CellularLinkPropertiesResponse, error)
	// Configures static IP or DHCP for an interface
	SetCellularConfig(context.Context, *CellularConfig) (*common.BooleanResponse, error)
	// Connects / activates the cellular connection
	Connect(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error)
	// Disconnects / deactivates the cellular connection
	Disconnect(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error)
	// Observes modem / network state changes
	SubscribeCellularEvents(*CellularInterfaceRequest, grpc.ServerStreamingServer[CellularLinkProperties]) error
	mustEmbedUnimplementedCellularServiceServer()
}

// UnimplementedCellularServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellularServiceServer struct{}

func (UnimplementedCellularServiceServer) ListCellularInterfaces(context.Context, *common.Empty) (*CellularInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCellularInterfaces not implemented")
}
func (UnimplementedCellularServiceServer) IsCellularConnected(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsCellularConnected not implemented")
}
func (UnimplementedCellularServiceServer) GetCellularLinkProperties(context.Context, *CellularInterfaceRequest) (*CellularLinkPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCellularLinkProperties not implemented")
}
func (UnimplementedCellularServiceServer) SetCellularConfig(context.Context, *CellularConfig) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCellularConfig not implemented")
}
func (UnimplementedCellularServiceServer) Connect(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCellularServiceServer) Disconnect(context.Context, *CellularInterfaceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedCellularServiceServer) SubscribeCellularEvents(*CellularInterfaceRequest, grpc.ServerStreamingServer[CellularLinkProperties]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCellularEvents not implemented")
}
func (UnimplementedCellularServiceServer) mustEmbedUnimplementedCellularServiceServer() {}
func (UnimplementedCellularServiceServer) testEmbeddedByValue()                         {}

// UnsafeCellularServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellularServiceServer will
// result in compilation errors.
type UnsafeCellularServiceServer interface {
	mustEmbedUnimplementedCellularServiceServer()
}

func RegisterCellularServiceServer(s grpc.ServiceRegistrar, srv CellularServiceServer) {
	// If the following call panics, it indicates UnimplementedCellularServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellularService_ServiceDesc, srv)
}

func _CellularService_ListCellularInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).ListCellularInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_ListCellularInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).ListCellularInterfaces(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_IsCellularConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellularInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).IsCellularConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_IsCellularConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).IsCellularConnected(ctx, req.(*CellularInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_GetCellularLinkProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellularInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).GetCellularLinkProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_GetCellularLinkProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).GetCellularLinkProperties(ctx, req.(*CellularInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_SetCellularConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellularConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).SetCellularConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_SetCellularConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).SetCellularConfig(ctx, req.(*CellularConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellularInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).Connect(ctx, req.(*CellularInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellularInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellularServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellularService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellularServiceServer).Disconnect(ctx, req.(*CellularInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellularService_SubscribeCellularEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CellularInterfaceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CellularServiceServer).SubscribeCellularEvents(m, &grpc.GenericServerStream[CellularInterfaceRequest, CellularLinkProperties]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CellularService_SubscribeCellularEventsServer = grpc.ServerStreamingServer[CellularLinkProperties]

// CellularService_ServiceDesc is the grpc.ServiceDesc for CellularService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellularService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.CellularService",
	HandlerType: (*CellularServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCellularInterfaces",
			Handler:    _CellularService_ListCellularInterfaces_Handler,
		},
		{
			MethodName: "IsCellularConnected",
			Handler:    _CellularService_IsCellularConnected_Handler,
		},
		{
			MethodName: "GetCellularLinkProperties",
			Handler:    _CellularService_GetCellularLinkProperties_Handler,
		},
		{
			MethodName: "SetCellularConfig",
			Handler:    _CellularService_SetCellularConfig_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _CellularService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _CellularService_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCellularEvents",
			Handler:       _CellularService_SubscribeCellularEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cellular_service/v26/cellular_service.proto",
}
