// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: common/types.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_NONE              ErrorCode = 0 // No error
	ErrorCode_ERROR_CODE_UNSPECIFIED       ErrorCode = 1 // Unspecified error
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT  ErrorCode = 2 // Invalid argument
	ErrorCode_ERROR_CODE_NOT_FOUND         ErrorCode = 3 // Resource not found
	ErrorCode_ERROR_CODE_ALREADY_EXISTS    ErrorCode = 4 // Already exists
	ErrorCode_ERROR_CODE_INTERNAL          ErrorCode = 5 // Internal error
	ErrorCode_ERROR_CODE_UNAVAILABLE       ErrorCode = 6 // Service or resource unavailable
	ErrorCode_ERROR_CODE_TIMEOUT           ErrorCode = 7 // Operation timed out
	ErrorCode_ERROR_CODE_UNIMPLEMENTED     ErrorCode = 8 // Feature not implemented
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 9 // Permission denied
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_NONE",
		1: "ERROR_CODE_UNSPECIFIED",
		2: "ERROR_CODE_INVALID_ARGUMENT",
		3: "ERROR_CODE_NOT_FOUND",
		4: "ERROR_CODE_ALREADY_EXISTS",
		5: "ERROR_CODE_INTERNAL",
		6: "ERROR_CODE_UNAVAILABLE",
		7: "ERROR_CODE_TIMEOUT",
		8: "ERROR_CODE_UNIMPLEMENTED",
		9: "ERROR_CODE_PERMISSION_DENIED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_NONE":              0,
		"ERROR_CODE_UNSPECIFIED":       1,
		"ERROR_CODE_INVALID_ARGUMENT":  2,
		"ERROR_CODE_NOT_FOUND":         3,
		"ERROR_CODE_ALREADY_EXISTS":    4,
		"ERROR_CODE_INTERNAL":          5,
		"ERROR_CODE_UNAVAILABLE":       6,
		"ERROR_CODE_TIMEOUT":           7,
		"ERROR_CODE_UNIMPLEMENTED":     8,
		"ERROR_CODE_PERMISSION_DENIED": 9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.gravity.types.ErrorCode" json:"code,omitempty"` // Error code (0 = no error)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                             // Optional message (explanation or detail)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

type StringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringRequest) Reset() {
	*x = StringRequest{}
	mi := &file_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRequest) ProtoMessage() {}

func (x *StringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRequest.ProtoReflect.Descriptor instead.
func (*StringRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *StringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	mi := &file_common_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{4}
}

func (x *StringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type IntegerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerResponse) Reset() {
	*x = IntegerResponse{}
	mi := &file_common_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerResponse) ProtoMessage() {}

func (x *IntegerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerResponse.ProtoReflect.Descriptor instead.
func (*IntegerResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{5}
}

func (x *IntegerResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntegerResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type UInt64Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInt64Response) Reset() {
	*x = UInt64Response{}
	mi := &file_common_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt64Response) ProtoMessage() {}

func (x *UInt64Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt64Response.ProtoReflect.Descriptor instead.
func (*UInt64Response) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{6}
}

func (x *UInt64Response) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UInt64Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type DoubleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleResponse) Reset() {
	*x = DoubleResponse{}
	mi := &file_common_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleResponse) ProtoMessage() {}

func (x *DoubleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleResponse.ProtoReflect.Descriptor instead.
func (*DoubleResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{7}
}

func (x *DoubleResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DoubleResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type BooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanResponse) Reset() {
	*x = BooleanResponse{}
	mi := &file_common_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanResponse) ProtoMessage() {}

func (x *BooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanResponse.ProtoReflect.Descriptor instead.
func (*BooleanResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{8}
}

func (x *BooleanResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *BooleanResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type APIVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIVersionResponse) Reset() {
	*x = APIVersionResponse{}
	mi := &file_common_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIVersionResponse) ProtoMessage() {}

func (x *APIVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIVersionResponse.ProtoReflect.Descriptor instead.
func (*APIVersionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{9}
}

func (x *APIVersionResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *APIVersionResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *APIVersionResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common/types.proto\x12\x11api.gravity.types\"W\n" +
	"\tErrorInfo\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.api.gravity.types.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"\x06\n" +
	"\x04Void\"%\n" +
	"\rStringRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"Z\n" +
	"\x0eStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"[\n" +
	"\x0fIntegerResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"Z\n" +
	"\x0eUInt64Response\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"Z\n" +
	"\x0eDoubleResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"[\n" +
	"\x0fBooleanResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"~\n" +
	"\x12APIVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error*\xa3\x02\n" +
	"\tErrorCode\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x00\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x01\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x03\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x05\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x06\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\a\x12\x1c\n" +
	"\x18ERROR_CODE_UNIMPLEMENTED\x10\b\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\tb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_types_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: api.gravity.types.ErrorCode
	(*ErrorInfo)(nil),          // 1: api.gravity.types.ErrorInfo
	(*Empty)(nil),              // 2: api.gravity.types.Empty
	(*Void)(nil),               // 3: api.gravity.types.Void
	(*StringRequest)(nil),      // 4: api.gravity.types.StringRequest
	(*StringResponse)(nil),     // 5: api.gravity.types.StringResponse
	(*IntegerResponse)(nil),    // 6: api.gravity.types.IntegerResponse
	(*UInt64Response)(nil),     // 7: api.gravity.types.UInt64Response
	(*DoubleResponse)(nil),     // 8: api.gravity.types.DoubleResponse
	(*BooleanResponse)(nil),    // 9: api.gravity.types.BooleanResponse
	(*APIVersionResponse)(nil), // 10: api.gravity.types.APIVersionResponse
}
var file_common_types_proto_depIdxs = []int32{
	0, // 0: api.gravity.types.ErrorInfo.code:type_name -> api.gravity.types.ErrorCode
	1, // 1: api.gravity.types.StringResponse.error:type_name -> api.gravity.types.ErrorInfo
	1, // 2: api.gravity.types.IntegerResponse.error:type_name -> api.gravity.types.ErrorInfo
	1, // 3: api.gravity.types.UInt64Response.error:type_name -> api.gravity.types.ErrorInfo
	1, // 4: api.gravity.types.DoubleResponse.error:type_name -> api.gravity.types.ErrorInfo
	1, // 5: api.gravity.types.BooleanResponse.error:type_name -> api.gravity.types.ErrorInfo
	1, // 6: api.gravity.types.APIVersionResponse.error:type_name -> api.gravity.types.ErrorInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
