// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: firewall_service/v26/firewall_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FirewallService_ListZones_FullMethodName     = "/api.gravity.v26.FirewallService/ListZones"
	FirewallService_AddZone_FullMethodName       = "/api.gravity.v26.FirewallService/AddZone"
	FirewallService_RemoveZone_FullMethodName    = "/api.gravity.v26.FirewallService/RemoveZone"
	FirewallService_ListRules_FullMethodName     = "/api.gravity.v26.FirewallService/ListRules"
	FirewallService_AddRule_FullMethodName       = "/api.gravity.v26.FirewallService/AddRule"
	FirewallService_RemoveRule_FullMethodName    = "/api.gravity.v26.FirewallService/RemoveRule"
	FirewallService_FlushRules_FullMethodName    = "/api.gravity.v26.FirewallService/FlushRules"
	FirewallService_ApplyFirewall_FullMethodName = "/api.gravity.v26.FirewallService/ApplyFirewall"
)

// FirewallServiceClient is the client API for FirewallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirewallServiceClient interface {
	// Zonas
	ListZones(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ZonesResponse, error)
	AddZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	RemoveZone(ctx context.Context, in *ZoneNameRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Regras de tráfego (exceções às políticas da zona)
	ListRules(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*FirewallRulesResponse, error)
	AddRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	RemoveRule(ctx context.Context, in *FirewallRuleIdRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	FlushRules(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Datapath: aplica a configuração persistida (zonas + regras) ao firewall em execução numa transação.
	ApplyFirewall(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
}

type firewallServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewallServiceClient(cc grpc.ClientConnInterface) FirewallServiceClient {
	return &firewallServiceClient{cc}
}

func (c *firewallServiceClient) ListZones(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZonesResponse)
	err := c.cc.Invoke(ctx, FirewallService_ListZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) AddZone(ctx context.Context, in *ZoneRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_AddZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) RemoveZone(ctx context.Context, in *ZoneNameRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_RemoveZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) ListRules(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*FirewallRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallRulesResponse)
	err := c.cc.Invoke(ctx, FirewallService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) AddRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) RemoveRule(ctx context.Context, in *FirewallRuleIdRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_RemoveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) FlushRules(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_FlushRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallServiceClient) ApplyFirewall(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, FirewallService_ApplyFirewall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewallServiceServer is the server API for FirewallService service.
// All implementations must embed UnimplementedFirewallServiceServer
// for forward compatibility.
type FirewallServiceServer interface {
	// Zonas
	ListZones(context.Context, *common.Empty) (*ZonesResponse, error)
	AddZone(context.Context, *ZoneRequest) (*common.BooleanResponse, error)
	RemoveZone(context.Context, *ZoneNameRequest) (*common.BooleanResponse, error)
	// Regras de tráfego (exceções às políticas da zona)
	ListRules(context.Context, *common.Empty) (*FirewallRulesResponse, error)
	AddRule(context.Context, *FirewallRuleRequest) (*common.BooleanResponse, error)
	RemoveRule(context.Context, *FirewallRuleIdRequest) (*common.BooleanResponse, error)
	FlushRules(context.Context, *common.Empty) (*common.BooleanResponse, error)
	// Datapath: aplica a configuração persistida (zonas + regras) ao firewall em execução numa transação.
	ApplyFirewall(context.Context, *common.Empty) (*common.BooleanResponse, error)
	mustEmbedUnimplementedFirewallServiceServer()
}

// UnimplementedFirewallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirewallServiceServer struct{}

func (UnimplementedFirewallServiceServer) ListZones(context.Context, *common.Empty) (*ZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZones not implemented")
}
func (UnimplementedFirewallServiceServer) AddZone(context.Context, *ZoneRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddZone not implemented")
}
func (UnimplementedFirewallServiceServer) RemoveZone(context.Context, *ZoneNameRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveZone not implemented")
}
func (UnimplementedFirewallServiceServer) ListRules(context.Context, *common.Empty) (*FirewallRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedFirewallServiceServer) AddRule(context.Context, *FirewallRuleRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedFirewallServiceServer) RemoveRule(context.Context, *FirewallRuleIdRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRule not implemented")
}
func (UnimplementedFirewallServiceServer) FlushRules(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushRules not implemented")
}
func (UnimplementedFirewallServiceServer) ApplyFirewall(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyFirewall not implemented")
}
func (UnimplementedFirewallServiceServer) mustEmbedUnimplementedFirewallServiceServer() {}
func (UnimplementedFirewallServiceServer) testEmbeddedByValue()                         {}

// UnsafeFirewallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewallServiceServer will
// result in compilation errors.
type UnsafeFirewallServiceServer interface {
	mustEmbedUnimplementedFirewallServiceServer()
}

func RegisterFirewallServiceServer(s grpc.ServiceRegistrar, srv FirewallServiceServer) {
	// If the following call panics, it indicates UnimplementedFirewallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirewallService_ServiceDesc, srv)
}

func _FirewallService_ListZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).ListZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_ListZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).ListZones(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_AddZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).AddZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_AddZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).AddZone(ctx, req.(*ZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_RemoveZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).RemoveZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_RemoveZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).RemoveZone(ctx, req.(*ZoneNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).ListRules(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).AddRule(ctx, req.(*FirewallRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallRuleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_RemoveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).RemoveRule(ctx, req.(*FirewallRuleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_FlushRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).FlushRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_FlushRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).FlushRules(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallService_ApplyFirewall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallServiceServer).ApplyFirewall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallService_ApplyFirewall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallServiceServer).ApplyFirewall(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewallService_ServiceDesc is the grpc.ServiceDesc for FirewallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.FirewallService",
	HandlerType: (*FirewallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListZones",
			Handler:    _FirewallService_ListZones_Handler,
		},
		{
			MethodName: "AddZone",
			Handler:    _FirewallService_AddZone_Handler,
		},
		{
			MethodName: "RemoveZone",
			Handler:    _FirewallService_RemoveZone_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _FirewallService_ListRules_Handler,
		},
		{
			MethodName: "AddRule",
			Handler:    _FirewallService_AddRule_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _FirewallService_RemoveRule_Handler,
		},
		{
			MethodName: "FlushRules",
			Handler:    _FirewallService_FlushRules_Handler,
		},
		{
			MethodName: "ApplyFirewall",
			Handler:    _FirewallService_ApplyFirewall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firewall_service/v26/firewall_service.proto",
}
