// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: uart_service/v26/uart_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UartService_ListUartPorts_FullMethodName = "/api.gravity.v26.UartService/ListUartPorts"
	UartService_OpenUart_FullMethodName      = "/api.gravity.v26.UartService/OpenUart"
	UartService_CloseUart_FullMethodName     = "/api.gravity.v26.UartService/CloseUart"
	UartService_GetUartConfig_FullMethodName = "/api.gravity.v26.UartService/GetUartConfig"
	UartService_WriteUart_FullMethodName     = "/api.gravity.v26.UartService/WriteUart"
	UartService_ListenUart_FullMethodName    = "/api.gravity.v26.UartService/ListenUart"
)

// UartServiceClient is the client API for UartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UartServiceClient interface {
	// UART
	ListUartPorts(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListUartPortsResponse, error)
	OpenUart(ctx context.Context, in *UartConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	CloseUart(ctx context.Context, in *UartPortRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GetUartConfig(ctx context.Context, in *UartPortRequest, opts ...grpc.CallOption) (*UartConfigResponse, error)
	WriteUart(ctx context.Context, in *UartWriteRequest, opts ...grpc.CallOption) (*UartWriteResponse, error)
	ListenUart(ctx context.Context, in *UartReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UartReadChunk], error)
}

type uartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUartServiceClient(cc grpc.ClientConnInterface) UartServiceClient {
	return &uartServiceClient{cc}
}

func (c *uartServiceClient) ListUartPorts(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListUartPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUartPortsResponse)
	err := c.cc.Invoke(ctx, UartService_ListUartPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uartServiceClient) OpenUart(ctx context.Context, in *UartConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, UartService_OpenUart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uartServiceClient) CloseUart(ctx context.Context, in *UartPortRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, UartService_CloseUart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uartServiceClient) GetUartConfig(ctx context.Context, in *UartPortRequest, opts ...grpc.CallOption) (*UartConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UartConfigResponse)
	err := c.cc.Invoke(ctx, UartService_GetUartConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uartServiceClient) WriteUart(ctx context.Context, in *UartWriteRequest, opts ...grpc.CallOption) (*UartWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UartWriteResponse)
	err := c.cc.Invoke(ctx, UartService_WriteUart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uartServiceClient) ListenUart(ctx context.Context, in *UartReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UartReadChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UartService_ServiceDesc.Streams[0], UartService_ListenUart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UartReadRequest, UartReadChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UartService_ListenUartClient = grpc.ServerStreamingClient[UartReadChunk]

// UartServiceServer is the server API for UartService service.
// All implementations must embed UnimplementedUartServiceServer
// for forward compatibility.
type UartServiceServer interface {
	// UART
	ListUartPorts(context.Context, *common.Void) (*ListUartPortsResponse, error)
	OpenUart(context.Context, *UartConfigRequest) (*common.BooleanResponse, error)
	CloseUart(context.Context, *UartPortRequest) (*common.BooleanResponse, error)
	GetUartConfig(context.Context, *UartPortRequest) (*UartConfigResponse, error)
	WriteUart(context.Context, *UartWriteRequest) (*UartWriteResponse, error)
	ListenUart(*UartReadRequest, grpc.ServerStreamingServer[UartReadChunk]) error
	mustEmbedUnimplementedUartServiceServer()
}

// UnimplementedUartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUartServiceServer struct{}

func (UnimplementedUartServiceServer) ListUartPorts(context.Context, *common.Void) (*ListUartPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUartPorts not implemented")
}
func (UnimplementedUartServiceServer) OpenUart(context.Context, *UartConfigRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenUart not implemented")
}
func (UnimplementedUartServiceServer) CloseUart(context.Context, *UartPortRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseUart not implemented")
}
func (UnimplementedUartServiceServer) GetUartConfig(context.Context, *UartPortRequest) (*UartConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUartConfig not implemented")
}
func (UnimplementedUartServiceServer) WriteUart(context.Context, *UartWriteRequest) (*UartWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteUart not implemented")
}
func (UnimplementedUartServiceServer) ListenUart(*UartReadRequest, grpc.ServerStreamingServer[UartReadChunk]) error {
	return status.Error(codes.Unimplemented, "method ListenUart not implemented")
}
func (UnimplementedUartServiceServer) mustEmbedUnimplementedUartServiceServer() {}
func (UnimplementedUartServiceServer) testEmbeddedByValue()                     {}

// UnsafeUartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UartServiceServer will
// result in compilation errors.
type UnsafeUartServiceServer interface {
	mustEmbedUnimplementedUartServiceServer()
}

func RegisterUartServiceServer(s grpc.ServiceRegistrar, srv UartServiceServer) {
	// If the following call panics, it indicates UnimplementedUartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UartService_ServiceDesc, srv)
}

func _UartService_ListUartPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UartServiceServer).ListUartPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UartService_ListUartPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UartServiceServer).ListUartPorts(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _UartService_OpenUart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UartConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UartServiceServer).OpenUart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UartService_OpenUart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UartServiceServer).OpenUart(ctx, req.(*UartConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UartService_CloseUart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UartPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UartServiceServer).CloseUart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UartService_CloseUart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UartServiceServer).CloseUart(ctx, req.(*UartPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UartService_GetUartConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UartPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UartServiceServer).GetUartConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UartService_GetUartConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UartServiceServer).GetUartConfig(ctx, req.(*UartPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UartService_WriteUart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UartWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UartServiceServer).WriteUart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UartService_WriteUart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UartServiceServer).WriteUart(ctx, req.(*UartWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UartService_ListenUart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UartReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UartServiceServer).ListenUart(m, &grpc.GenericServerStream[UartReadRequest, UartReadChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UartService_ListenUartServer = grpc.ServerStreamingServer[UartReadChunk]

// UartService_ServiceDesc is the grpc.ServiceDesc for UartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.UartService",
	HandlerType: (*UartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUartPorts",
			Handler:    _UartService_ListUartPorts_Handler,
		},
		{
			MethodName: "OpenUart",
			Handler:    _UartService_OpenUart_Handler,
		},
		{
			MethodName: "CloseUart",
			Handler:    _UartService_CloseUart_Handler,
		},
		{
			MethodName: "GetUartConfig",
			Handler:    _UartService_GetUartConfig_Handler,
		},
		{
			MethodName: "WriteUart",
			Handler:    _UartService_WriteUart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenUart",
			Handler:       _UartService_ListenUart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "uart_service/v26/uart_service.proto",
}
