// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: bluetooth_service/v26/bluetooth_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BluetoothService_GetAdapterInfo_FullMethodName              = "/api.gravity.v26.BluetoothService/GetAdapterInfo"
	BluetoothService_EnableBluetooth_FullMethodName             = "/api.gravity.v26.BluetoothService/EnableBluetooth"
	BluetoothService_DisableBluetooth_FullMethodName            = "/api.gravity.v26.BluetoothService/DisableBluetooth"
	BluetoothService_GetLocalName_FullMethodName                = "/api.gravity.v26.BluetoothService/GetLocalName"
	BluetoothService_SetLocalName_FullMethodName                = "/api.gravity.v26.BluetoothService/SetLocalName"
	BluetoothService_SetDiscoverable_FullMethodName             = "/api.gravity.v26.BluetoothService/SetDiscoverable"
	BluetoothService_StartScan_FullMethodName                   = "/api.gravity.v26.BluetoothService/StartScan"
	BluetoothService_GetBondedDevices_FullMethodName            = "/api.gravity.v26.BluetoothService/GetBondedDevices"
	BluetoothService_BondDevice_FullMethodName                  = "/api.gravity.v26.BluetoothService/BondDevice"
	BluetoothService_RemoveBond_FullMethodName                  = "/api.gravity.v26.BluetoothService/RemoveBond"
	BluetoothService_ConnectDevice_FullMethodName               = "/api.gravity.v26.BluetoothService/ConnectDevice"
	BluetoothService_DisconnectDevice_FullMethodName            = "/api.gravity.v26.BluetoothService/DisconnectDevice"
	BluetoothService_GetConnectionState_FullMethodName          = "/api.gravity.v26.BluetoothService/GetConnectionState"
	BluetoothService_StartBleScan_FullMethodName                = "/api.gravity.v26.BluetoothService/StartBleScan"
	BluetoothService_GattConnect_FullMethodName                 = "/api.gravity.v26.BluetoothService/GattConnect"
	BluetoothService_GattDisconnect_FullMethodName              = "/api.gravity.v26.BluetoothService/GattDisconnect"
	BluetoothService_GetGattState_FullMethodName                = "/api.gravity.v26.BluetoothService/GetGattState"
	BluetoothService_GattDiscoverServices_FullMethodName        = "/api.gravity.v26.BluetoothService/GattDiscoverServices"
	BluetoothService_GattReadCharacteristic_FullMethodName      = "/api.gravity.v26.BluetoothService/GattReadCharacteristic"
	BluetoothService_GattWriteCharacteristic_FullMethodName     = "/api.gravity.v26.BluetoothService/GattWriteCharacteristic"
	BluetoothService_GattSubscribeCharacteristic_FullMethodName = "/api.gravity.v26.BluetoothService/GattSubscribeCharacteristic"
	BluetoothService_GattReadDescriptor_FullMethodName          = "/api.gravity.v26.BluetoothService/GattReadDescriptor"
	BluetoothService_GattWriteDescriptor_FullMethodName         = "/api.gravity.v26.BluetoothService/GattWriteDescriptor"
	BluetoothService_GattReadRssi_FullMethodName                = "/api.gravity.v26.BluetoothService/GattReadRssi"
	BluetoothService_RequestMtu_FullMethodName                  = "/api.gravity.v26.BluetoothService/RequestMtu"
	BluetoothService_RequestConnectionPriority_FullMethodName   = "/api.gravity.v26.BluetoothService/RequestConnectionPriority"
	BluetoothService_SetPreferredPhy_FullMethodName             = "/api.gravity.v26.BluetoothService/SetPreferredPhy"
	BluetoothService_ReadPhy_FullMethodName                     = "/api.gravity.v26.BluetoothService/ReadPhy"
	BluetoothService_StartAdvertising_FullMethodName            = "/api.gravity.v26.BluetoothService/StartAdvertising"
	BluetoothService_StopAdvertising_FullMethodName             = "/api.gravity.v26.BluetoothService/StopAdvertising"
)

// BluetoothServiceClient is the client API for BluetoothService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BluetoothServiceClient interface {
	// Adapter
	GetAdapterInfo(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BluetoothAdapterInfoResponse, error)
	EnableBluetooth(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	DisableBluetooth(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GetLocalName(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.StringResponse, error)
	SetLocalName(ctx context.Context, in *common.StringRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	SetDiscoverable(ctx context.Context, in *SetDiscoverableRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Classic Bluetooth — discovery
	// Stream ends when the adapter finishes discovery or the client cancels the RPC
	StartScan(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClassicScanResult], error)
	GetBondedDevices(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BondedDevicesResponse, error)
	// Classic Bluetooth — pairing
	// BondDevice streams pairing events (state changes, PIN requests) until bonding completes
	BondDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BondEvent], error)
	RemoveBond(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Classic Bluetooth — connection (profile-agnostic)
	ConnectDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	DisconnectDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GetConnectionState(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*BtConnectionStateResponse, error)
	// BLE — scan
	// Stream delivers results continuously; cancel the RPC to stop scanning
	StartBleScan(ctx context.Context, in *BleScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BleScanResult], error)
	// BLE — GATT client: lifecycle
	GattConnect(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GattDisconnect(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GetGattState(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattStateResponse, error)
	// BLE — GATT client: service & characteristic operations
	GattDiscoverServices(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattServicesResponse, error)
	GattReadCharacteristic(ctx context.Context, in *GattReadRequest, opts ...grpc.CallOption) (*GattReadResponse, error)
	GattWriteCharacteristic(ctx context.Context, in *GattWriteRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GattSubscribeCharacteristic(ctx context.Context, in *GattSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GattNotification], error)
	// BLE — GATT client: descriptor operations (e.g. manual CCCD management)
	GattReadDescriptor(ctx context.Context, in *GattDescriptorRequest, opts ...grpc.CallOption) (*GattDescriptorReadResponse, error)
	GattWriteDescriptor(ctx context.Context, in *GattDescriptorWriteRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// BLE — GATT client: link tuning
	GattReadRssi(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattRssiResponse, error)
	RequestMtu(ctx context.Context, in *MtuRequest, opts ...grpc.CallOption) (*MtuResponse, error)
	RequestConnectionPriority(ctx context.Context, in *ConnectionPriorityRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	SetPreferredPhy(ctx context.Context, in *PhyRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	ReadPhy(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*PhyResponse, error)
	// BLE — advertising (Pi acts as peripheral)
	StartAdvertising(ctx context.Context, in *AdvertiseRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	StopAdvertising(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
}

type bluetoothServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBluetoothServiceClient(cc grpc.ClientConnInterface) BluetoothServiceClient {
	return &bluetoothServiceClient{cc}
}

func (c *bluetoothServiceClient) GetAdapterInfo(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BluetoothAdapterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BluetoothAdapterInfoResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GetAdapterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) EnableBluetooth(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_EnableBluetooth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) DisableBluetooth(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_DisableBluetooth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GetLocalName(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.StringResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GetLocalName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) SetLocalName(ctx context.Context, in *common.StringRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_SetLocalName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) SetDiscoverable(ctx context.Context, in *SetDiscoverableRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_SetDiscoverable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) StartScan(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClassicScanResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BluetoothService_ServiceDesc.Streams[0], BluetoothService_StartScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.Empty, ClassicScanResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_StartScanClient = grpc.ServerStreamingClient[ClassicScanResult]

func (c *bluetoothServiceClient) GetBondedDevices(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*BondedDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BondedDevicesResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GetBondedDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) BondDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BondEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BluetoothService_ServiceDesc.Streams[1], BluetoothService_BondDevice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BtDeviceRequest, BondEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_BondDeviceClient = grpc.ServerStreamingClient[BondEvent]

func (c *bluetoothServiceClient) RemoveBond(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_RemoveBond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) ConnectDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_ConnectDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) DisconnectDevice(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_DisconnectDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GetConnectionState(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*BtConnectionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BtConnectionStateResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GetConnectionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) StartBleScan(ctx context.Context, in *BleScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BleScanResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BluetoothService_ServiceDesc.Streams[2], BluetoothService_StartBleScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BleScanRequest, BleScanResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_StartBleScanClient = grpc.ServerStreamingClient[BleScanResult]

func (c *bluetoothServiceClient) GattConnect(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattDisconnect(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattDisconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GetGattState(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GattStateResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GetGattState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattDiscoverServices(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GattServicesResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattDiscoverServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattReadCharacteristic(ctx context.Context, in *GattReadRequest, opts ...grpc.CallOption) (*GattReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GattReadResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattReadCharacteristic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattWriteCharacteristic(ctx context.Context, in *GattWriteRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattWriteCharacteristic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattSubscribeCharacteristic(ctx context.Context, in *GattSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GattNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BluetoothService_ServiceDesc.Streams[3], BluetoothService_GattSubscribeCharacteristic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GattSubscribeRequest, GattNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_GattSubscribeCharacteristicClient = grpc.ServerStreamingClient[GattNotification]

func (c *bluetoothServiceClient) GattReadDescriptor(ctx context.Context, in *GattDescriptorRequest, opts ...grpc.CallOption) (*GattDescriptorReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GattDescriptorReadResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattReadDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattWriteDescriptor(ctx context.Context, in *GattDescriptorWriteRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattWriteDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) GattReadRssi(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*GattRssiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GattRssiResponse)
	err := c.cc.Invoke(ctx, BluetoothService_GattReadRssi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) RequestMtu(ctx context.Context, in *MtuRequest, opts ...grpc.CallOption) (*MtuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MtuResponse)
	err := c.cc.Invoke(ctx, BluetoothService_RequestMtu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) RequestConnectionPriority(ctx context.Context, in *ConnectionPriorityRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_RequestConnectionPriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) SetPreferredPhy(ctx context.Context, in *PhyRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_SetPreferredPhy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) ReadPhy(ctx context.Context, in *BtDeviceRequest, opts ...grpc.CallOption) (*PhyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhyResponse)
	err := c.cc.Invoke(ctx, BluetoothService_ReadPhy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) StartAdvertising(ctx context.Context, in *AdvertiseRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_StartAdvertising_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothServiceClient) StopAdvertising(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, BluetoothService_StopAdvertising_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BluetoothServiceServer is the server API for BluetoothService service.
// All implementations must embed UnimplementedBluetoothServiceServer
// for forward compatibility.
type BluetoothServiceServer interface {
	// Adapter
	GetAdapterInfo(context.Context, *common.Empty) (*BluetoothAdapterInfoResponse, error)
	EnableBluetooth(context.Context, *common.Empty) (*common.BooleanResponse, error)
	DisableBluetooth(context.Context, *common.Empty) (*common.BooleanResponse, error)
	GetLocalName(context.Context, *common.Empty) (*common.StringResponse, error)
	SetLocalName(context.Context, *common.StringRequest) (*common.BooleanResponse, error)
	SetDiscoverable(context.Context, *SetDiscoverableRequest) (*common.BooleanResponse, error)
	// Classic Bluetooth — discovery
	// Stream ends when the adapter finishes discovery or the client cancels the RPC
	StartScan(*common.Empty, grpc.ServerStreamingServer[ClassicScanResult]) error
	GetBondedDevices(context.Context, *common.Empty) (*BondedDevicesResponse, error)
	// Classic Bluetooth — pairing
	// BondDevice streams pairing events (state changes, PIN requests) until bonding completes
	BondDevice(*BtDeviceRequest, grpc.ServerStreamingServer[BondEvent]) error
	RemoveBond(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error)
	// Classic Bluetooth — connection (profile-agnostic)
	ConnectDevice(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error)
	DisconnectDevice(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error)
	GetConnectionState(context.Context, *BtDeviceRequest) (*BtConnectionStateResponse, error)
	// BLE — scan
	// Stream delivers results continuously; cancel the RPC to stop scanning
	StartBleScan(*BleScanRequest, grpc.ServerStreamingServer[BleScanResult]) error
	// BLE — GATT client: lifecycle
	GattConnect(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error)
	GattDisconnect(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error)
	GetGattState(context.Context, *BtDeviceRequest) (*GattStateResponse, error)
	// BLE — GATT client: service & characteristic operations
	GattDiscoverServices(context.Context, *BtDeviceRequest) (*GattServicesResponse, error)
	GattReadCharacteristic(context.Context, *GattReadRequest) (*GattReadResponse, error)
	GattWriteCharacteristic(context.Context, *GattWriteRequest) (*common.BooleanResponse, error)
	GattSubscribeCharacteristic(*GattSubscribeRequest, grpc.ServerStreamingServer[GattNotification]) error
	// BLE — GATT client: descriptor operations (e.g. manual CCCD management)
	GattReadDescriptor(context.Context, *GattDescriptorRequest) (*GattDescriptorReadResponse, error)
	GattWriteDescriptor(context.Context, *GattDescriptorWriteRequest) (*common.BooleanResponse, error)
	// BLE — GATT client: link tuning
	GattReadRssi(context.Context, *BtDeviceRequest) (*GattRssiResponse, error)
	RequestMtu(context.Context, *MtuRequest) (*MtuResponse, error)
	RequestConnectionPriority(context.Context, *ConnectionPriorityRequest) (*common.BooleanResponse, error)
	SetPreferredPhy(context.Context, *PhyRequest) (*common.BooleanResponse, error)
	ReadPhy(context.Context, *BtDeviceRequest) (*PhyResponse, error)
	// BLE — advertising (Pi acts as peripheral)
	StartAdvertising(context.Context, *AdvertiseRequest) (*common.BooleanResponse, error)
	StopAdvertising(context.Context, *common.Empty) (*common.BooleanResponse, error)
	mustEmbedUnimplementedBluetoothServiceServer()
}

// UnimplementedBluetoothServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBluetoothServiceServer struct{}

func (UnimplementedBluetoothServiceServer) GetAdapterInfo(context.Context, *common.Empty) (*BluetoothAdapterInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdapterInfo not implemented")
}
func (UnimplementedBluetoothServiceServer) EnableBluetooth(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableBluetooth not implemented")
}
func (UnimplementedBluetoothServiceServer) DisableBluetooth(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableBluetooth not implemented")
}
func (UnimplementedBluetoothServiceServer) GetLocalName(context.Context, *common.Empty) (*common.StringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocalName not implemented")
}
func (UnimplementedBluetoothServiceServer) SetLocalName(context.Context, *common.StringRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLocalName not implemented")
}
func (UnimplementedBluetoothServiceServer) SetDiscoverable(context.Context, *SetDiscoverableRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDiscoverable not implemented")
}
func (UnimplementedBluetoothServiceServer) StartScan(*common.Empty, grpc.ServerStreamingServer[ClassicScanResult]) error {
	return status.Error(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedBluetoothServiceServer) GetBondedDevices(context.Context, *common.Empty) (*BondedDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBondedDevices not implemented")
}
func (UnimplementedBluetoothServiceServer) BondDevice(*BtDeviceRequest, grpc.ServerStreamingServer[BondEvent]) error {
	return status.Error(codes.Unimplemented, "method BondDevice not implemented")
}
func (UnimplementedBluetoothServiceServer) RemoveBond(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBond not implemented")
}
func (UnimplementedBluetoothServiceServer) ConnectDevice(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectDevice not implemented")
}
func (UnimplementedBluetoothServiceServer) DisconnectDevice(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectDevice not implemented")
}
func (UnimplementedBluetoothServiceServer) GetConnectionState(context.Context, *BtDeviceRequest) (*BtConnectionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionState not implemented")
}
func (UnimplementedBluetoothServiceServer) StartBleScan(*BleScanRequest, grpc.ServerStreamingServer[BleScanResult]) error {
	return status.Error(codes.Unimplemented, "method StartBleScan not implemented")
}
func (UnimplementedBluetoothServiceServer) GattConnect(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattConnect not implemented")
}
func (UnimplementedBluetoothServiceServer) GattDisconnect(context.Context, *BtDeviceRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattDisconnect not implemented")
}
func (UnimplementedBluetoothServiceServer) GetGattState(context.Context, *BtDeviceRequest) (*GattStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGattState not implemented")
}
func (UnimplementedBluetoothServiceServer) GattDiscoverServices(context.Context, *BtDeviceRequest) (*GattServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattDiscoverServices not implemented")
}
func (UnimplementedBluetoothServiceServer) GattReadCharacteristic(context.Context, *GattReadRequest) (*GattReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattReadCharacteristic not implemented")
}
func (UnimplementedBluetoothServiceServer) GattWriteCharacteristic(context.Context, *GattWriteRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattWriteCharacteristic not implemented")
}
func (UnimplementedBluetoothServiceServer) GattSubscribeCharacteristic(*GattSubscribeRequest, grpc.ServerStreamingServer[GattNotification]) error {
	return status.Error(codes.Unimplemented, "method GattSubscribeCharacteristic not implemented")
}
func (UnimplementedBluetoothServiceServer) GattReadDescriptor(context.Context, *GattDescriptorRequest) (*GattDescriptorReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattReadDescriptor not implemented")
}
func (UnimplementedBluetoothServiceServer) GattWriteDescriptor(context.Context, *GattDescriptorWriteRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattWriteDescriptor not implemented")
}
func (UnimplementedBluetoothServiceServer) GattReadRssi(context.Context, *BtDeviceRequest) (*GattRssiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GattReadRssi not implemented")
}
func (UnimplementedBluetoothServiceServer) RequestMtu(context.Context, *MtuRequest) (*MtuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestMtu not implemented")
}
func (UnimplementedBluetoothServiceServer) RequestConnectionPriority(context.Context, *ConnectionPriorityRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestConnectionPriority not implemented")
}
func (UnimplementedBluetoothServiceServer) SetPreferredPhy(context.Context, *PhyRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPreferredPhy not implemented")
}
func (UnimplementedBluetoothServiceServer) ReadPhy(context.Context, *BtDeviceRequest) (*PhyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPhy not implemented")
}
func (UnimplementedBluetoothServiceServer) StartAdvertising(context.Context, *AdvertiseRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAdvertising not implemented")
}
func (UnimplementedBluetoothServiceServer) StopAdvertising(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAdvertising not implemented")
}
func (UnimplementedBluetoothServiceServer) mustEmbedUnimplementedBluetoothServiceServer() {}
func (UnimplementedBluetoothServiceServer) testEmbeddedByValue()                          {}

// UnsafeBluetoothServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BluetoothServiceServer will
// result in compilation errors.
type UnsafeBluetoothServiceServer interface {
	mustEmbedUnimplementedBluetoothServiceServer()
}

func RegisterBluetoothServiceServer(s grpc.ServiceRegistrar, srv BluetoothServiceServer) {
	// If the following call panics, it indicates UnimplementedBluetoothServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BluetoothService_ServiceDesc, srv)
}

func _BluetoothService_GetAdapterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GetAdapterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GetAdapterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GetAdapterInfo(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_EnableBluetooth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).EnableBluetooth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_EnableBluetooth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).EnableBluetooth(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_DisableBluetooth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).DisableBluetooth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_DisableBluetooth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).DisableBluetooth(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GetLocalName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GetLocalName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GetLocalName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GetLocalName(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_SetLocalName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).SetLocalName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_SetLocalName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).SetLocalName(ctx, req.(*common.StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_SetDiscoverable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDiscoverableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).SetDiscoverable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_SetDiscoverable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).SetDiscoverable(ctx, req.(*SetDiscoverableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_StartScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BluetoothServiceServer).StartScan(m, &grpc.GenericServerStream[common.Empty, ClassicScanResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_StartScanServer = grpc.ServerStreamingServer[ClassicScanResult]

func _BluetoothService_GetBondedDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GetBondedDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GetBondedDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GetBondedDevices(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_BondDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BtDeviceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BluetoothServiceServer).BondDevice(m, &grpc.GenericServerStream[BtDeviceRequest, BondEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_BondDeviceServer = grpc.ServerStreamingServer[BondEvent]

func _BluetoothService_RemoveBond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).RemoveBond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_RemoveBond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).RemoveBond(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_ConnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).ConnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_ConnectDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).ConnectDevice(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_DisconnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).DisconnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_DisconnectDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).DisconnectDevice(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GetConnectionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GetConnectionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GetConnectionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GetConnectionState(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_StartBleScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BleScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BluetoothServiceServer).StartBleScan(m, &grpc.GenericServerStream[BleScanRequest, BleScanResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_StartBleScanServer = grpc.ServerStreamingServer[BleScanResult]

func _BluetoothService_GattConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattConnect(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattDisconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattDisconnect(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GetGattState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GetGattState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GetGattState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GetGattState(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattDiscoverServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattDiscoverServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattDiscoverServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattDiscoverServices(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattReadCharacteristic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GattReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattReadCharacteristic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattReadCharacteristic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattReadCharacteristic(ctx, req.(*GattReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattWriteCharacteristic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GattWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattWriteCharacteristic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattWriteCharacteristic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattWriteCharacteristic(ctx, req.(*GattWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattSubscribeCharacteristic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GattSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BluetoothServiceServer).GattSubscribeCharacteristic(m, &grpc.GenericServerStream[GattSubscribeRequest, GattNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BluetoothService_GattSubscribeCharacteristicServer = grpc.ServerStreamingServer[GattNotification]

func _BluetoothService_GattReadDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GattDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattReadDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattReadDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattReadDescriptor(ctx, req.(*GattDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattWriteDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GattDescriptorWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattWriteDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattWriteDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattWriteDescriptor(ctx, req.(*GattDescriptorWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_GattReadRssi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).GattReadRssi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_GattReadRssi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).GattReadRssi(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_RequestMtu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MtuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).RequestMtu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_RequestMtu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).RequestMtu(ctx, req.(*MtuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_RequestConnectionPriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).RequestConnectionPriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_RequestConnectionPriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).RequestConnectionPriority(ctx, req.(*ConnectionPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_SetPreferredPhy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).SetPreferredPhy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_SetPreferredPhy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).SetPreferredPhy(ctx, req.(*PhyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_ReadPhy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).ReadPhy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_ReadPhy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).ReadPhy(ctx, req.(*BtDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_StartAdvertising_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).StartAdvertising(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_StartAdvertising_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).StartAdvertising(ctx, req.(*AdvertiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BluetoothService_StopAdvertising_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServiceServer).StopAdvertising(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BluetoothService_StopAdvertising_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServiceServer).StopAdvertising(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BluetoothService_ServiceDesc is the grpc.ServiceDesc for BluetoothService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BluetoothService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.BluetoothService",
	HandlerType: (*BluetoothServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdapterInfo",
			Handler:    _BluetoothService_GetAdapterInfo_Handler,
		},
		{
			MethodName: "EnableBluetooth",
			Handler:    _BluetoothService_EnableBluetooth_Handler,
		},
		{
			MethodName: "DisableBluetooth",
			Handler:    _BluetoothService_DisableBluetooth_Handler,
		},
		{
			MethodName: "GetLocalName",
			Handler:    _BluetoothService_GetLocalName_Handler,
		},
		{
			MethodName: "SetLocalName",
			Handler:    _BluetoothService_SetLocalName_Handler,
		},
		{
			MethodName: "SetDiscoverable",
			Handler:    _BluetoothService_SetDiscoverable_Handler,
		},
		{
			MethodName: "GetBondedDevices",
			Handler:    _BluetoothService_GetBondedDevices_Handler,
		},
		{
			MethodName: "RemoveBond",
			Handler:    _BluetoothService_RemoveBond_Handler,
		},
		{
			MethodName: "ConnectDevice",
			Handler:    _BluetoothService_ConnectDevice_Handler,
		},
		{
			MethodName: "DisconnectDevice",
			Handler:    _BluetoothService_DisconnectDevice_Handler,
		},
		{
			MethodName: "GetConnectionState",
			Handler:    _BluetoothService_GetConnectionState_Handler,
		},
		{
			MethodName: "GattConnect",
			Handler:    _BluetoothService_GattConnect_Handler,
		},
		{
			MethodName: "GattDisconnect",
			Handler:    _BluetoothService_GattDisconnect_Handler,
		},
		{
			MethodName: "GetGattState",
			Handler:    _BluetoothService_GetGattState_Handler,
		},
		{
			MethodName: "GattDiscoverServices",
			Handler:    _BluetoothService_GattDiscoverServices_Handler,
		},
		{
			MethodName: "GattReadCharacteristic",
			Handler:    _BluetoothService_GattReadCharacteristic_Handler,
		},
		{
			MethodName: "GattWriteCharacteristic",
			Handler:    _BluetoothService_GattWriteCharacteristic_Handler,
		},
		{
			MethodName: "GattReadDescriptor",
			Handler:    _BluetoothService_GattReadDescriptor_Handler,
		},
		{
			MethodName: "GattWriteDescriptor",
			Handler:    _BluetoothService_GattWriteDescriptor_Handler,
		},
		{
			MethodName: "GattReadRssi",
			Handler:    _BluetoothService_GattReadRssi_Handler,
		},
		{
			MethodName: "RequestMtu",
			Handler:    _BluetoothService_RequestMtu_Handler,
		},
		{
			MethodName: "RequestConnectionPriority",
			Handler:    _BluetoothService_RequestConnectionPriority_Handler,
		},
		{
			MethodName: "SetPreferredPhy",
			Handler:    _BluetoothService_SetPreferredPhy_Handler,
		},
		{
			MethodName: "ReadPhy",
			Handler:    _BluetoothService_ReadPhy_Handler,
		},
		{
			MethodName: "StartAdvertising",
			Handler:    _BluetoothService_StartAdvertising_Handler,
		},
		{
			MethodName: "StopAdvertising",
			Handler:    _BluetoothService_StopAdvertising_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartScan",
			Handler:       _BluetoothService_StartScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BondDevice",
			Handler:       _BluetoothService_BondDevice_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartBleScan",
			Handler:       _BluetoothService_StartBleScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GattSubscribeCharacteristic",
			Handler:       _BluetoothService_GattSubscribeCharacteristic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bluetooth_service/v26/bluetooth_service.proto",
}
