// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: camera_service/v26/camera_service.proto

package v26

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CameraService_CaptureImage_FullMethodName  = "/api.gravity.v26.CameraService/CaptureImage"
	CameraService_StreamFrames_FullMethodName  = "/api.gravity.v26.CameraService/StreamFrames"
	CameraService_LockCamera_FullMethodName    = "/api.gravity.v26.CameraService/LockCamera"
	CameraService_UnlockCamera_FullMethodName  = "/api.gravity.v26.CameraService/UnlockCamera"
	CameraService_GetDeviceInfo_FullMethodName = "/api.gravity.v26.CameraService/GetDeviceInfo"
	CameraService_ListDevices_FullMethodName   = "/api.gravity.v26.CameraService/ListDevices"
)

// CameraServiceClient is the client API for CameraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CameraServiceClient interface {
	// 📸 Captura uma única imagem
	CaptureImage(ctx context.Context, in *CaptureImageRequest, opts ...grpc.CallOption) (*CaptureImageResponse, error)
	// 🎥 Stream contínuo (FPS camera)
	StreamFrames(ctx context.Context, in *StreamFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
	// 🔒 Lock da câmara (evita acesso concorrente)
	LockCamera(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	// 🔓 Libertar câmara
	UnlockCamera(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	// ℹ️ Informação do device
	GetDeviceInfo(ctx context.Context, in *DeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfoResponse, error)
	// 📋 Lista todos os dispositivos V4L2 disponíveis no sistema
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
}

type cameraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCameraServiceClient(cc grpc.ClientConnInterface) CameraServiceClient {
	return &cameraServiceClient{cc}
}

func (c *cameraServiceClient) CaptureImage(ctx context.Context, in *CaptureImageRequest, opts ...grpc.CallOption) (*CaptureImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureImageResponse)
	err := c.cc.Invoke(ctx, CameraService_CaptureImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraServiceClient) StreamFrames(ctx context.Context, in *StreamFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CameraService_ServiceDesc.Streams[0], CameraService_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFramesRequest, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraService_StreamFramesClient = grpc.ServerStreamingClient[Frame]

func (c *cameraServiceClient) LockCamera(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, CameraService_LockCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraServiceClient) UnlockCamera(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, CameraService_UnlockCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraServiceClient) GetDeviceInfo(ctx context.Context, in *DeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceInfoResponse)
	err := c.cc.Invoke(ctx, CameraService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, CameraService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CameraServiceServer is the server API for CameraService service.
// All implementations must embed UnimplementedCameraServiceServer
// for forward compatibility.
type CameraServiceServer interface {
	// 📸 Captura uma única imagem
	CaptureImage(context.Context, *CaptureImageRequest) (*CaptureImageResponse, error)
	// 🎥 Stream contínuo (FPS camera)
	StreamFrames(*StreamFramesRequest, grpc.ServerStreamingServer[Frame]) error
	// 🔒 Lock da câmara (evita acesso concorrente)
	LockCamera(context.Context, *LockRequest) (*LockResponse, error)
	// 🔓 Libertar câmara
	UnlockCamera(context.Context, *UnlockRequest) (*UnlockResponse, error)
	// ℹ️ Informação do device
	GetDeviceInfo(context.Context, *DeviceInfoRequest) (*DeviceInfoResponse, error)
	// 📋 Lista todos os dispositivos V4L2 disponíveis no sistema
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	mustEmbedUnimplementedCameraServiceServer()
}

// UnimplementedCameraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCameraServiceServer struct{}

func (UnimplementedCameraServiceServer) CaptureImage(context.Context, *CaptureImageRequest) (*CaptureImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureImage not implemented")
}
func (UnimplementedCameraServiceServer) StreamFrames(*StreamFramesRequest, grpc.ServerStreamingServer[Frame]) error {
	return status.Error(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedCameraServiceServer) LockCamera(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockCamera not implemented")
}
func (UnimplementedCameraServiceServer) UnlockCamera(context.Context, *UnlockRequest) (*UnlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockCamera not implemented")
}
func (UnimplementedCameraServiceServer) GetDeviceInfo(context.Context, *DeviceInfoRequest) (*DeviceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedCameraServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedCameraServiceServer) mustEmbedUnimplementedCameraServiceServer() {}
func (UnimplementedCameraServiceServer) testEmbeddedByValue()                       {}

// UnsafeCameraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CameraServiceServer will
// result in compilation errors.
type UnsafeCameraServiceServer interface {
	mustEmbedUnimplementedCameraServiceServer()
}

func RegisterCameraServiceServer(s grpc.ServiceRegistrar, srv CameraServiceServer) {
	// If the following call panics, it indicates UnimplementedCameraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CameraService_ServiceDesc, srv)
}

func _CameraService_CaptureImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServiceServer).CaptureImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraService_CaptureImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServiceServer).CaptureImage(ctx, req.(*CaptureImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraService_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFramesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CameraServiceServer).StreamFrames(m, &grpc.GenericServerStream[StreamFramesRequest, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraService_StreamFramesServer = grpc.ServerStreamingServer[Frame]

func _CameraService_LockCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServiceServer).LockCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraService_LockCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServiceServer).LockCamera(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraService_UnlockCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServiceServer).UnlockCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraService_UnlockCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServiceServer).UnlockCamera(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServiceServer).GetDeviceInfo(ctx, req.(*DeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CameraService_ServiceDesc is the grpc.ServiceDesc for CameraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CameraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.CameraService",
	HandlerType: (*CameraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureImage",
			Handler:    _CameraService_CaptureImage_Handler,
		},
		{
			MethodName: "LockCamera",
			Handler:    _CameraService_LockCamera_Handler,
		},
		{
			MethodName: "UnlockCamera",
			Handler:    _CameraService_UnlockCamera_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _CameraService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _CameraService_ListDevices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrames",
			Handler:       _CameraService_StreamFrames_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "camera_service/v26/camera_service.proto",
}
