// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: camera_service/v26/camera_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptureImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // ex: "/dev/video0"
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // "mjpeg", "yuyv"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureImageRequest) Reset() {
	*x = CaptureImageRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureImageRequest) ProtoMessage() {}

func (x *CaptureImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureImageRequest.ProtoReflect.Descriptor instead.
func (*CaptureImageRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{0}
}

func (x *CaptureImageRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CaptureImageRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CaptureImageRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptureImageRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type CaptureImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // JPEG final
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureImageResponse) Reset() {
	*x = CaptureImageResponse{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureImageResponse) ProtoMessage() {}

func (x *CaptureImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureImageResponse.ProtoReflect.Descriptor instead.
func (*CaptureImageResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CaptureImageResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *CaptureImageResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CaptureImageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CaptureImageResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type StreamFramesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Fps           int32                  `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFramesRequest) Reset() {
	*x = StreamFramesRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFramesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFramesRequest) ProtoMessage() {}

func (x *StreamFramesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFramesRequest.ProtoReflect.Descriptor instead.
func (*StreamFramesRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamFramesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StreamFramesRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *StreamFramesRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StreamFramesRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{3}
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Frame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Frame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Frame) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{4}
}

func (x *LockRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LockRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{5}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{6}
}

func (x *UnlockRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UnlockRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{7}
}

func (x *UnlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeviceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoRequest) Reset() {
	*x = DeviceInfoRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoRequest) ProtoMessage() {}

func (x *DeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfoRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Driver           string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Card             string                 `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	SupportedFormats []string               `protobuf:"bytes,4,rep,name=supported_formats,json=supportedFormats,proto3" json:"supported_formats,omitempty"`
	Resolutions      []string               `protobuf:"bytes,5,rep,name=resolutions,proto3" json:"resolutions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceInfoResponse) Reset() {
	*x = DeviceInfoResponse{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoResponse) ProtoMessage() {}

func (x *DeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*DeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceInfoResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfoResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DeviceInfoResponse) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *DeviceInfoResponse) GetSupportedFormats() []string {
	if x != nil {
		return x.SupportedFormats
	}
	return nil
}

func (x *DeviceInfoResponse) GetResolutions() []string {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{10}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfoResponse  `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_v26_camera_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_v26_camera_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfoResponse {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_camera_service_v26_camera_service_proto protoreflect.FileDescriptor

const file_camera_service_v26_camera_service_proto_rawDesc = "" +
	"\n" +
	"'camera_service/v26/camera_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"x\n" +
	"\x13CaptureImageRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xb9\x01\n" +
	"\x14CaptureImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"r\n" +
	"\x13StreamFramesRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x05R\x03fps\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x7f\n" +
	"\x05Frame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"G\n" +
	"\vLockRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\\\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"I\n" +
	"\rUnlockRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"^\n" +
	"\x0eUnlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"0\n" +
	"\x11DeviceInfoRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xac\x01\n" +
	"\x12DeviceInfoResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x12\n" +
	"\x04card\x18\x03 \x01(\tR\x04card\x12+\n" +
	"\x11supported_formats\x18\x04 \x03(\tR\x10supportedFormats\x12 \n" +
	"\vresolutions\x18\x05 \x03(\tR\vresolutions\"\x14\n" +
	"\x12ListDevicesRequest\"T\n" +
	"\x13ListDevicesResponse\x12=\n" +
	"\adevices\x18\x01 \x03(\v2#.api.gravity.v26.DeviceInfoResponseR\adevices2\x8c\x04\n" +
	"\rCameraService\x12[\n" +
	"\fCaptureImage\x12$.api.gravity.v26.CaptureImageRequest\x1a%.api.gravity.v26.CaptureImageResponse\x12N\n" +
	"\fStreamFrames\x12$.api.gravity.v26.StreamFramesRequest\x1a\x16.api.gravity.v26.Frame0\x01\x12I\n" +
	"\n" +
	"LockCamera\x12\x1c.api.gravity.v26.LockRequest\x1a\x1d.api.gravity.v26.LockResponse\x12O\n" +
	"\fUnlockCamera\x12\x1e.api.gravity.v26.UnlockRequest\x1a\x1f.api.gravity.v26.UnlockResponse\x12X\n" +
	"\rGetDeviceInfo\x12\".api.gravity.v26.DeviceInfoRequest\x1a#.api.gravity.v26.DeviceInfoResponse\x12X\n" +
	"\vListDevices\x12#.api.gravity.v26.ListDevicesRequest\x1a$.api.gravity.v26.ListDevicesResponseb\x06proto3"

var (
	file_camera_service_v26_camera_service_proto_rawDescOnce sync.Once
	file_camera_service_v26_camera_service_proto_rawDescData []byte
)

func file_camera_service_v26_camera_service_proto_rawDescGZIP() []byte {
	file_camera_service_v26_camera_service_proto_rawDescOnce.Do(func() {
		file_camera_service_v26_camera_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_camera_service_v26_camera_service_proto_rawDesc), len(file_camera_service_v26_camera_service_proto_rawDesc)))
	})
	return file_camera_service_v26_camera_service_proto_rawDescData
}

var file_camera_service_v26_camera_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_camera_service_v26_camera_service_proto_goTypes = []any{
	(*CaptureImageRequest)(nil),  // 0: api.gravity.v26.CaptureImageRequest
	(*CaptureImageResponse)(nil), // 1: api.gravity.v26.CaptureImageResponse
	(*StreamFramesRequest)(nil),  // 2: api.gravity.v26.StreamFramesRequest
	(*Frame)(nil),                // 3: api.gravity.v26.Frame
	(*LockRequest)(nil),          // 4: api.gravity.v26.LockRequest
	(*LockResponse)(nil),         // 5: api.gravity.v26.LockResponse
	(*UnlockRequest)(nil),        // 6: api.gravity.v26.UnlockRequest
	(*UnlockResponse)(nil),       // 7: api.gravity.v26.UnlockResponse
	(*DeviceInfoRequest)(nil),    // 8: api.gravity.v26.DeviceInfoRequest
	(*DeviceInfoResponse)(nil),   // 9: api.gravity.v26.DeviceInfoResponse
	(*ListDevicesRequest)(nil),   // 10: api.gravity.v26.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 11: api.gravity.v26.ListDevicesResponse
	(*common.ErrorInfo)(nil),     // 12: api.gravity.types.ErrorInfo
}
var file_camera_service_v26_camera_service_proto_depIdxs = []int32{
	12, // 0: api.gravity.v26.CaptureImageResponse.error:type_name -> api.gravity.types.ErrorInfo
	12, // 1: api.gravity.v26.LockResponse.error:type_name -> api.gravity.types.ErrorInfo
	12, // 2: api.gravity.v26.UnlockResponse.error:type_name -> api.gravity.types.ErrorInfo
	9,  // 3: api.gravity.v26.ListDevicesResponse.devices:type_name -> api.gravity.v26.DeviceInfoResponse
	0,  // 4: api.gravity.v26.CameraService.CaptureImage:input_type -> api.gravity.v26.CaptureImageRequest
	2,  // 5: api.gravity.v26.CameraService.StreamFrames:input_type -> api.gravity.v26.StreamFramesRequest
	4,  // 6: api.gravity.v26.CameraService.LockCamera:input_type -> api.gravity.v26.LockRequest
	6,  // 7: api.gravity.v26.CameraService.UnlockCamera:input_type -> api.gravity.v26.UnlockRequest
	8,  // 8: api.gravity.v26.CameraService.GetDeviceInfo:input_type -> api.gravity.v26.DeviceInfoRequest
	10, // 9: api.gravity.v26.CameraService.ListDevices:input_type -> api.gravity.v26.ListDevicesRequest
	1,  // 10: api.gravity.v26.CameraService.CaptureImage:output_type -> api.gravity.v26.CaptureImageResponse
	3,  // 11: api.gravity.v26.CameraService.StreamFrames:output_type -> api.gravity.v26.Frame
	5,  // 12: api.gravity.v26.CameraService.LockCamera:output_type -> api.gravity.v26.LockResponse
	7,  // 13: api.gravity.v26.CameraService.UnlockCamera:output_type -> api.gravity.v26.UnlockResponse
	9,  // 14: api.gravity.v26.CameraService.GetDeviceInfo:output_type -> api.gravity.v26.DeviceInfoResponse
	11, // 15: api.gravity.v26.CameraService.ListDevices:output_type -> api.gravity.v26.ListDevicesResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_camera_service_v26_camera_service_proto_init() }
func file_camera_service_v26_camera_service_proto_init() {
	if File_camera_service_v26_camera_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_camera_service_v26_camera_service_proto_rawDesc), len(file_camera_service_v26_camera_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camera_service_v26_camera_service_proto_goTypes,
		DependencyIndexes: file_camera_service_v26_camera_service_proto_depIdxs,
		MessageInfos:      file_camera_service_v26_camera_service_proto_msgTypes,
	}.Build()
	File_camera_service_v26_camera_service_proto = out.File
	file_camera_service_v26_camera_service_proto_goTypes = nil
	file_camera_service_v26_camera_service_proto_depIdxs = nil
}
