// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: time_service/v26/time_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeService_GetNTPConfig_FullMethodName     = "/api.gravity.v26.TimeService/GetNTPConfig"
	TimeService_SetNTPConfig_FullMethodName     = "/api.gravity.v26.TimeService/SetNTPConfig"
	TimeService_IsNTPSyncEnabled_FullMethodName = "/api.gravity.v26.TimeService/IsNTPSyncEnabled"
	TimeService_EnableNTPSync_FullMethodName    = "/api.gravity.v26.TimeService/EnableNTPSync"
	TimeService_DisableNTPSync_FullMethodName   = "/api.gravity.v26.TimeService/DisableNTPSync"
	TimeService_GetTimeSeconds_FullMethodName   = "/api.gravity.v26.TimeService/GetTimeSeconds"
	TimeService_SetTimeSeconds_FullMethodName   = "/api.gravity.v26.TimeService/SetTimeSeconds"
	TimeService_GetTimeMillis_FullMethodName    = "/api.gravity.v26.TimeService/GetTimeMillis"
	TimeService_SetTimeMillis_FullMethodName    = "/api.gravity.v26.TimeService/SetTimeMillis"
	TimeService_GetUptime_FullMethodName        = "/api.gravity.v26.TimeService/GetUptime"
)

// TimeServiceClient is the client API for TimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeServiceClient interface {
	// NTP config — atomic, applies all settings in one reload
	GetNTPConfig(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NTPConfigResponse, error)
	SetNTPConfig(ctx context.Context, in *NTPConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// NTP Sync — convenience wrappers (internally call SetNTPConfig)
	IsNTPSyncEnabled(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	EnableNTPSync(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	DisableNTPSync(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Time
	GetTimeSeconds(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetTimeResponse, error)
	SetTimeSeconds(ctx context.Context, in *SetTimeRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	GetTimeMillis(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetTimeResponse, error)
	SetTimeMillis(ctx context.Context, in *SetTimeRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Uptime
	GetUptime(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UptimeResponse, error)
}

type timeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeServiceClient(cc grpc.ClientConnInterface) TimeServiceClient {
	return &timeServiceClient{cc}
}

func (c *timeServiceClient) GetNTPConfig(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NTPConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NTPConfigResponse)
	err := c.cc.Invoke(ctx, TimeService_GetNTPConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) SetNTPConfig(ctx context.Context, in *NTPConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_SetNTPConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) IsNTPSyncEnabled(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_IsNTPSyncEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) EnableNTPSync(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_EnableNTPSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) DisableNTPSync(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_DisableNTPSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) GetTimeSeconds(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeResponse)
	err := c.cc.Invoke(ctx, TimeService_GetTimeSeconds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) SetTimeSeconds(ctx context.Context, in *SetTimeRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_SetTimeSeconds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) GetTimeMillis(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeResponse)
	err := c.cc.Invoke(ctx, TimeService_GetTimeMillis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) SetTimeMillis(ctx context.Context, in *SetTimeRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, TimeService_SetTimeMillis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeServiceClient) GetUptime(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeResponse)
	err := c.cc.Invoke(ctx, TimeService_GetUptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeServiceServer is the server API for TimeService service.
// All implementations must embed UnimplementedTimeServiceServer
// for forward compatibility.
type TimeServiceServer interface {
	// NTP config — atomic, applies all settings in one reload
	GetNTPConfig(context.Context, *common.Empty) (*NTPConfigResponse, error)
	SetNTPConfig(context.Context, *NTPConfigRequest) (*common.BooleanResponse, error)
	// NTP Sync — convenience wrappers (internally call SetNTPConfig)
	IsNTPSyncEnabled(context.Context, *common.Empty) (*common.BooleanResponse, error)
	EnableNTPSync(context.Context, *common.Empty) (*common.BooleanResponse, error)
	DisableNTPSync(context.Context, *common.Empty) (*common.BooleanResponse, error)
	// Time
	GetTimeSeconds(context.Context, *common.Empty) (*GetTimeResponse, error)
	SetTimeSeconds(context.Context, *SetTimeRequest) (*common.BooleanResponse, error)
	GetTimeMillis(context.Context, *common.Empty) (*GetTimeResponse, error)
	SetTimeMillis(context.Context, *SetTimeRequest) (*common.BooleanResponse, error)
	// Uptime
	GetUptime(context.Context, *common.Empty) (*UptimeResponse, error)
	mustEmbedUnimplementedTimeServiceServer()
}

// UnimplementedTimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeServiceServer struct{}

func (UnimplementedTimeServiceServer) GetNTPConfig(context.Context, *common.Empty) (*NTPConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNTPConfig not implemented")
}
func (UnimplementedTimeServiceServer) SetNTPConfig(context.Context, *NTPConfigRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNTPConfig not implemented")
}
func (UnimplementedTimeServiceServer) IsNTPSyncEnabled(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsNTPSyncEnabled not implemented")
}
func (UnimplementedTimeServiceServer) EnableNTPSync(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableNTPSync not implemented")
}
func (UnimplementedTimeServiceServer) DisableNTPSync(context.Context, *common.Empty) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableNTPSync not implemented")
}
func (UnimplementedTimeServiceServer) GetTimeSeconds(context.Context, *common.Empty) (*GetTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeSeconds not implemented")
}
func (UnimplementedTimeServiceServer) SetTimeSeconds(context.Context, *SetTimeRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTimeSeconds not implemented")
}
func (UnimplementedTimeServiceServer) GetTimeMillis(context.Context, *common.Empty) (*GetTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeMillis not implemented")
}
func (UnimplementedTimeServiceServer) SetTimeMillis(context.Context, *SetTimeRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTimeMillis not implemented")
}
func (UnimplementedTimeServiceServer) GetUptime(context.Context, *common.Empty) (*UptimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUptime not implemented")
}
func (UnimplementedTimeServiceServer) mustEmbedUnimplementedTimeServiceServer() {}
func (UnimplementedTimeServiceServer) testEmbeddedByValue()                     {}

// UnsafeTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeServiceServer will
// result in compilation errors.
type UnsafeTimeServiceServer interface {
	mustEmbedUnimplementedTimeServiceServer()
}

func RegisterTimeServiceServer(s grpc.ServiceRegistrar, srv TimeServiceServer) {
	// If the following call panics, it indicates UnimplementedTimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeService_ServiceDesc, srv)
}

func _TimeService_GetNTPConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).GetNTPConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_GetNTPConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).GetNTPConfig(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_SetNTPConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NTPConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).SetNTPConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_SetNTPConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).SetNTPConfig(ctx, req.(*NTPConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_IsNTPSyncEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).IsNTPSyncEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_IsNTPSyncEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).IsNTPSyncEnabled(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_EnableNTPSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).EnableNTPSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_EnableNTPSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).EnableNTPSync(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_DisableNTPSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).DisableNTPSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_DisableNTPSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).DisableNTPSync(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_GetTimeSeconds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).GetTimeSeconds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_GetTimeSeconds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).GetTimeSeconds(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_SetTimeSeconds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).SetTimeSeconds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_SetTimeSeconds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).SetTimeSeconds(ctx, req.(*SetTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_GetTimeMillis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).GetTimeMillis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_GetTimeMillis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).GetTimeMillis(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_SetTimeMillis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).SetTimeMillis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_SetTimeMillis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).SetTimeMillis(ctx, req.(*SetTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeService_GetUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).GetUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_GetUptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).GetUptime(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeService_ServiceDesc is the grpc.ServiceDesc for TimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.TimeService",
	HandlerType: (*TimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNTPConfig",
			Handler:    _TimeService_GetNTPConfig_Handler,
		},
		{
			MethodName: "SetNTPConfig",
			Handler:    _TimeService_SetNTPConfig_Handler,
		},
		{
			MethodName: "IsNTPSyncEnabled",
			Handler:    _TimeService_IsNTPSyncEnabled_Handler,
		},
		{
			MethodName: "EnableNTPSync",
			Handler:    _TimeService_EnableNTPSync_Handler,
		},
		{
			MethodName: "DisableNTPSync",
			Handler:    _TimeService_DisableNTPSync_Handler,
		},
		{
			MethodName: "GetTimeSeconds",
			Handler:    _TimeService_GetTimeSeconds_Handler,
		},
		{
			MethodName: "SetTimeSeconds",
			Handler:    _TimeService_SetTimeSeconds_Handler,
		},
		{
			MethodName: "GetTimeMillis",
			Handler:    _TimeService_GetTimeMillis_Handler,
		},
		{
			MethodName: "SetTimeMillis",
			Handler:    _TimeService_SetTimeMillis_Handler,
		},
		{
			MethodName: "GetUptime",
			Handler:    _TimeService_GetUptime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "time_service/v26/time_service.proto",
}
