// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: update_service/v26/update_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	FileMd5       string                 `protobuf:"bytes,6,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_update_service_v26_update_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_update_service_v26_update_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_update_service_v26_update_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *FileChunk) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *FileChunk) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

var File_update_service_v26_update_service_proto protoreflect.FileDescriptor

const file_update_service_v26_update_service_proto_rawDesc = "" +
	"\n" +
	"'update_service/v26/update_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"\xd2\x01\n" +
	"\tFileChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\x12\x19\n" +
	"\bfile_md5\x18\x06 \x01(\tR\afileMd5\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize2\xa9\x01\n" +
	"\rUpdateService\x12L\n" +
	"\fFactoryReset\x12\x18.api.gravity.types.Empty\x1a\".api.gravity.types.BooleanResponse\x12J\n" +
	"\x06Update\x12\x1a.api.gravity.v26.FileChunk\x1a\".api.gravity.types.BooleanResponse(\x01b\x06proto3"

var (
	file_update_service_v26_update_service_proto_rawDescOnce sync.Once
	file_update_service_v26_update_service_proto_rawDescData []byte
)

func file_update_service_v26_update_service_proto_rawDescGZIP() []byte {
	file_update_service_v26_update_service_proto_rawDescOnce.Do(func() {
		file_update_service_v26_update_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_service_v26_update_service_proto_rawDesc), len(file_update_service_v26_update_service_proto_rawDesc)))
	})
	return file_update_service_v26_update_service_proto_rawDescData
}

var file_update_service_v26_update_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_update_service_v26_update_service_proto_goTypes = []any{
	(*FileChunk)(nil),              // 0: api.gravity.v26.FileChunk
	(*common.Empty)(nil),           // 1: api.gravity.types.Empty
	(*common.BooleanResponse)(nil), // 2: api.gravity.types.BooleanResponse
}
var file_update_service_v26_update_service_proto_depIdxs = []int32{
	1, // 0: api.gravity.v26.UpdateService.FactoryReset:input_type -> api.gravity.types.Empty
	0, // 1: api.gravity.v26.UpdateService.Update:input_type -> api.gravity.v26.FileChunk
	2, // 2: api.gravity.v26.UpdateService.FactoryReset:output_type -> api.gravity.types.BooleanResponse
	2, // 3: api.gravity.v26.UpdateService.Update:output_type -> api.gravity.types.BooleanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_service_v26_update_service_proto_init() }
func file_update_service_v26_update_service_proto_init() {
	if File_update_service_v26_update_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_service_v26_update_service_proto_rawDesc), len(file_update_service_v26_update_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_update_service_v26_update_service_proto_goTypes,
		DependencyIndexes: file_update_service_v26_update_service_proto_depIdxs,
		MessageInfos:      file_update_service_v26_update_service_proto_msgTypes,
	}.Build()
	File_update_service_v26_update_service_proto = out.File
	file_update_service_v26_update_service_proto_goTypes = nil
	file_update_service_v26_update_service_proto_depIdxs = nil
}
