// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: vpn_service/v26/vpn_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VPNService_GetCapabilities_FullMethodName = "/api.gravity.v26.VPNService/GetCapabilities"
	VPNService_ListProfiles_FullMethodName    = "/api.gravity.v26.VPNService/ListProfiles"
	VPNService_ApplyProfile_FullMethodName    = "/api.gravity.v26.VPNService/ApplyProfile"
	VPNService_RemoveProfile_FullMethodName   = "/api.gravity.v26.VPNService/RemoveProfile"
	VPNService_Connect_FullMethodName         = "/api.gravity.v26.VPNService/Connect"
	VPNService_Disconnect_FullMethodName      = "/api.gravity.v26.VPNService/Disconnect"
	VPNService_GetStatus_FullMethodName       = "/api.gravity.v26.VPNService/GetStatus"
	VPNService_ListSessions_FullMethodName    = "/api.gravity.v26.VPNService/ListSessions"
	VPNService_WatchEvents_FullMethodName     = "/api.gravity.v26.VPNService/WatchEvents"
)

// VPNServiceClient is the client API for VPNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VPNServiceClient interface {
	// Capabilities
	GetCapabilities(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*VpnCapabilitiesResponse, error)
	// Profiles
	ListProfiles(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*VpnProfilesResponse, error)
	ApplyProfile(ctx context.Context, in *ApplyProfileRequest, opts ...grpc.CallOption) (*ApplyProfileResponse, error)
	RemoveProfile(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Connection
	Connect(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	// Status
	GetStatus(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ListSessions(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*SessionsResponse, error)
	// Events
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VPNEvent], error)
}

type vPNServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVPNServiceClient(cc grpc.ClientConnInterface) VPNServiceClient {
	return &vPNServiceClient{cc}
}

func (c *vPNServiceClient) GetCapabilities(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*VpnCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnCapabilitiesResponse)
	err := c.cc.Invoke(ctx, VPNService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) ListProfiles(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*VpnProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnProfilesResponse)
	err := c.cc.Invoke(ctx, VPNService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) ApplyProfile(ctx context.Context, in *ApplyProfileRequest, opts ...grpc.CallOption) (*ApplyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProfileResponse)
	err := c.cc.Invoke(ctx, VPNService_ApplyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) RemoveProfile(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, VPNService_RemoveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Connect(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, VPNService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Disconnect(ctx context.Context, in *VpnProfileRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, VPNService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) GetStatus(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, VPNService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) ListSessions(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*SessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsResponse)
	err := c.cc.Invoke(ctx, VPNService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VPNEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VPNService_ServiceDesc.Streams[0], VPNService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, VPNEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_WatchEventsClient = grpc.ServerStreamingClient[VPNEvent]

// VPNServiceServer is the server API for VPNService service.
// All implementations must embed UnimplementedVPNServiceServer
// for forward compatibility.
type VPNServiceServer interface {
	// Capabilities
	GetCapabilities(context.Context, *common.Empty) (*VpnCapabilitiesResponse, error)
	// Profiles
	ListProfiles(context.Context, *common.Empty) (*VpnProfilesResponse, error)
	ApplyProfile(context.Context, *ApplyProfileRequest) (*ApplyProfileResponse, error)
	RemoveProfile(context.Context, *VpnProfileRequest) (*common.BooleanResponse, error)
	// Connection
	Connect(context.Context, *VpnProfileRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *VpnProfileRequest) (*common.BooleanResponse, error)
	// Status
	GetStatus(context.Context, *common.Empty) (*GetStatusResponse, error)
	ListSessions(context.Context, *common.Empty) (*SessionsResponse, error)
	// Events
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[VPNEvent]) error
	mustEmbedUnimplementedVPNServiceServer()
}

// UnimplementedVPNServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVPNServiceServer struct{}

func (UnimplementedVPNServiceServer) GetCapabilities(context.Context, *common.Empty) (*VpnCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedVPNServiceServer) ListProfiles(context.Context, *common.Empty) (*VpnProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedVPNServiceServer) ApplyProfile(context.Context, *ApplyProfileRequest) (*ApplyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyProfile not implemented")
}
func (UnimplementedVPNServiceServer) RemoveProfile(context.Context, *VpnProfileRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProfile not implemented")
}
func (UnimplementedVPNServiceServer) Connect(context.Context, *VpnProfileRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedVPNServiceServer) Disconnect(context.Context, *VpnProfileRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedVPNServiceServer) GetStatus(context.Context, *common.Empty) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedVPNServiceServer) ListSessions(context.Context, *common.Empty) (*SessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedVPNServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[VPNEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedVPNServiceServer) mustEmbedUnimplementedVPNServiceServer() {}
func (UnimplementedVPNServiceServer) testEmbeddedByValue()                    {}

// UnsafeVPNServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VPNServiceServer will
// result in compilation errors.
type UnsafeVPNServiceServer interface {
	mustEmbedUnimplementedVPNServiceServer()
}

func RegisterVPNServiceServer(s grpc.ServiceRegistrar, srv VPNServiceServer) {
	// If the following call panics, it indicates UnimplementedVPNServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VPNService_ServiceDesc, srv)
}

func _VPNService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).GetCapabilities(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ListProfiles(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_ApplyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ApplyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_ApplyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ApplyProfile(ctx, req.(*ApplyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_RemoveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).RemoveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_RemoveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).RemoveProfile(ctx, req.(*VpnProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Connect(ctx, req.(*VpnProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Disconnect(ctx, req.(*VpnProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).GetStatus(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VPNService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ListSessions(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VPNServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, VPNEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VPNService_WatchEventsServer = grpc.ServerStreamingServer[VPNEvent]

// VPNService_ServiceDesc is the grpc.ServiceDesc for VPNService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VPNService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.VPNService",
	HandlerType: (*VPNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _VPNService_GetCapabilities_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _VPNService_ListProfiles_Handler,
		},
		{
			MethodName: "ApplyProfile",
			Handler:    _VPNService_ApplyProfile_Handler,
		},
		{
			MethodName: "RemoveProfile",
			Handler:    _VPNService_RemoveProfile_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _VPNService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _VPNService_Disconnect_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _VPNService_GetStatus_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _VPNService_ListSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _VPNService_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vpn_service/v26/vpn_service.proto",
}
