// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: vpn_service/v26/vpn_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VpnProvider int32

const (
	VpnProvider_VPN_PROVIDER_UNSPECIFIED VpnProvider = 0
	VpnProvider_VPN_PROVIDER_WIREGUARD   VpnProvider = 1
	VpnProvider_VPN_PROVIDER_OPENVPN     VpnProvider = 2
	VpnProvider_VPN_PROVIDER_IPSEC       VpnProvider = 3
	VpnProvider_VPN_PROVIDER_CUSTOM      VpnProvider = 15
)

// Enum value maps for VpnProvider.
var (
	VpnProvider_name = map[int32]string{
		0:  "VPN_PROVIDER_UNSPECIFIED",
		1:  "VPN_PROVIDER_WIREGUARD",
		2:  "VPN_PROVIDER_OPENVPN",
		3:  "VPN_PROVIDER_IPSEC",
		15: "VPN_PROVIDER_CUSTOM",
	}
	VpnProvider_value = map[string]int32{
		"VPN_PROVIDER_UNSPECIFIED": 0,
		"VPN_PROVIDER_WIREGUARD":   1,
		"VPN_PROVIDER_OPENVPN":     2,
		"VPN_PROVIDER_IPSEC":       3,
		"VPN_PROVIDER_CUSTOM":      15,
	}
)

func (x VpnProvider) Enum() *VpnProvider {
	p := new(VpnProvider)
	*p = x
	return p
}

func (x VpnProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VpnProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_service_v26_vpn_service_proto_enumTypes[0].Descriptor()
}

func (VpnProvider) Type() protoreflect.EnumType {
	return &file_vpn_service_v26_vpn_service_proto_enumTypes[0]
}

func (x VpnProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VpnProvider.Descriptor instead.
func (VpnProvider) EnumDescriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{0}
}

type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNSPECIFIED TunnelState = 0
	TunnelState_TUNNEL_STATE_DOWN        TunnelState = 1
	TunnelState_TUNNEL_STATE_CONNECTING  TunnelState = 2
	TunnelState_TUNNEL_STATE_UP          TunnelState = 3
	TunnelState_TUNNEL_STATE_DEGRADED    TunnelState = 4
	TunnelState_TUNNEL_STATE_ERROR       TunnelState = 5
)

// Enum value maps for TunnelState.
var (
	TunnelState_name = map[int32]string{
		0: "TUNNEL_STATE_UNSPECIFIED",
		1: "TUNNEL_STATE_DOWN",
		2: "TUNNEL_STATE_CONNECTING",
		3: "TUNNEL_STATE_UP",
		4: "TUNNEL_STATE_DEGRADED",
		5: "TUNNEL_STATE_ERROR",
	}
	TunnelState_value = map[string]int32{
		"TUNNEL_STATE_UNSPECIFIED": 0,
		"TUNNEL_STATE_DOWN":        1,
		"TUNNEL_STATE_CONNECTING":  2,
		"TUNNEL_STATE_UP":          3,
		"TUNNEL_STATE_DEGRADED":    4,
		"TUNNEL_STATE_ERROR":       5,
	}
)

func (x TunnelState) Enum() *TunnelState {
	p := new(TunnelState)
	*p = x
	return p
}

func (x TunnelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelState) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_service_v26_vpn_service_proto_enumTypes[1].Descriptor()
}

func (TunnelState) Type() protoreflect.EnumType {
	return &file_vpn_service_v26_vpn_service_proto_enumTypes[1]
}

func (x TunnelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelState.Descriptor instead.
func (TunnelState) EnumDescriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{1}
}

// VPN profile — persisted configuration for a VPN provider.
// config_data holds the raw provider config file (WireGuard .conf, OpenVPN .ovpn, etc.)
type VpnProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Provider      VpnProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=api.gravity.v26.VpnProvider" json:"provider,omitempty"`
	ConfigData    []byte                 `protobuf:"bytes,4,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`     // raw provider config file
	AutoConnect   bool                   `protobuf:"varint,5,opt,name=auto_connect,json=autoConnect,proto3" json:"auto_connect,omitempty"` // connect automatically on boot / network up
	SecretRef     string                 `protobuf:"bytes,6,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`        // optional reference to secrets store (future-proofing)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnProfile) Reset() {
	*x = VpnProfile{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnProfile) ProtoMessage() {}

func (x *VpnProfile) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnProfile.ProtoReflect.Descriptor instead.
func (*VpnProfile) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{0}
}

func (x *VpnProfile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *VpnProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VpnProfile) GetProvider() VpnProvider {
	if x != nil {
		return x.Provider
	}
	return VpnProvider_VPN_PROVIDER_UNSPECIFIED
}

func (x *VpnProfile) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *VpnProfile) GetAutoConnect() bool {
	if x != nil {
		return x.AutoConnect
	}
	return false
}

func (x *VpnProfile) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProfileId       string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Provider        VpnProvider            `protobuf:"varint,3,opt,name=provider,proto3,enum=api.gravity.v26.VpnProvider" json:"provider,omitempty"`
	State           TunnelState            `protobuf:"varint,4,opt,name=state,proto3,enum=api.gravity.v26.TunnelState" json:"state,omitempty"`
	InterfaceName   string                 `protobuf:"bytes,5,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytes         uint64                 `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes         uint64                 `protobuf:"varint,7,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,8,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"` // Unix timestamp in milliseconds (UTC)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Session) GetProvider() VpnProvider {
	if x != nil {
		return x.Provider
	}
	return VpnProvider_VPN_PROVIDER_UNSPECIFIED
}

func (x *Session) GetState() TunnelState {
	if x != nil {
		return x.State
	}
	return TunnelState_TUNNEL_STATE_UNSPECIFIED
}

func (x *Session) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Session) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *Session) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *Session) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

type VpnProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnProfileRequest) Reset() {
	*x = VpnProfileRequest{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnProfileRequest) ProtoMessage() {}

func (x *VpnProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnProfileRequest.ProtoReflect.Descriptor instead.
func (*VpnProfileRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{2}
}

func (x *VpnProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ApplyProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Profile           *VpnProfile            `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ConnectAfterApply bool                   `protobuf:"varint,2,opt,name=connect_after_apply,json=connectAfterApply,proto3" json:"connect_after_apply,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyProfileRequest) Reset() {
	*x = ApplyProfileRequest{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfileRequest) ProtoMessage() {}

func (x *ApplyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfileRequest.ProtoReflect.Descriptor instead.
func (*ApplyProfileRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyProfileRequest) GetProfile() *VpnProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ApplyProfileRequest) GetConnectAfterApply() bool {
	if x != nil {
		return x.ConnectAfterApply
	}
	return false
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{4}
}

func (x *WatchEventsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type VpnCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wireguard     bool                   `protobuf:"varint,1,opt,name=wireguard,proto3" json:"wireguard,omitempty"` // WireGuard kernel module available
	Openvpn       bool                   `protobuf:"varint,2,opt,name=openvpn,proto3" json:"openvpn,omitempty"`     // OpenVPN binary available
	Ipsec         bool                   `protobuf:"varint,3,opt,name=ipsec,proto3" json:"ipsec,omitempty"`         // IPSec available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnCapabilities) Reset() {
	*x = VpnCapabilities{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnCapabilities) ProtoMessage() {}

func (x *VpnCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnCapabilities.ProtoReflect.Descriptor instead.
func (*VpnCapabilities) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{5}
}

func (x *VpnCapabilities) GetWireguard() bool {
	if x != nil {
		return x.Wireguard
	}
	return false
}

func (x *VpnCapabilities) GetOpenvpn() bool {
	if x != nil {
		return x.Openvpn
	}
	return false
}

func (x *VpnCapabilities) GetIpsec() bool {
	if x != nil {
		return x.Ipsec
	}
	return false
}

type VpnCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *VpnCapabilities       `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnCapabilitiesResponse) Reset() {
	*x = VpnCapabilitiesResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnCapabilitiesResponse) ProtoMessage() {}

func (x *VpnCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*VpnCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{6}
}

func (x *VpnCapabilitiesResponse) GetCapabilities() *VpnCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *VpnCapabilitiesResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type VpnProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*VpnProfile          `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnProfilesResponse) Reset() {
	*x = VpnProfilesResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnProfilesResponse) ProtoMessage() {}

func (x *VpnProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnProfilesResponse.ProtoReflect.Descriptor instead.
func (*VpnProfilesResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{7}
}

func (x *VpnProfilesResponse) GetProfiles() []*VpnProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *VpnProfilesResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type ApplyProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActiveProfileId string                 `protobuf:"bytes,1,opt,name=active_profile_id,json=activeProfileId,proto3" json:"active_profile_id,omitempty"`
	Error           *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyProfileResponse) Reset() {
	*x = ApplyProfileResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfileResponse) ProtoMessage() {}

func (x *ApplyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfileResponse.ProtoReflect.Descriptor instead.
func (*ApplyProfileResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyProfileResponse) GetActiveProfileId() string {
	if x != nil {
		return x.ActiveProfileId
	}
	return ""
}

func (x *ApplyProfileResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type SessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsResponse) Reset() {
	*x = SessionsResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsResponse) ProtoMessage() {}

func (x *SessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsResponse.ProtoReflect.Descriptor instead.
func (*SessionsResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{10}
}

func (x *SessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionsResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Session         *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ProviderDetails string                 `protobuf:"bytes,2,opt,name=provider_details,json=providerDetails,proto3" json:"provider_details,omitempty"` // JSON-encoded provider-specific data
	Error           *common.ErrorInfo      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetStatusResponse) GetProviderDetails() string {
	if x != nil {
		return x.ProviderDetails
	}
	return ""
}

func (x *GetStatusResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type VPNEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs  int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"` // Unix timestamp in milliseconds (UTC)
	ProfileId string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Provider  VpnProvider            `protobuf:"varint,4,opt,name=provider,proto3,enum=api.gravity.v26.VpnProvider" json:"provider,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VPNEvent_Tunnel
	//	*VPNEvent_ProviderEvent
	Payload       isVPNEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNEvent) Reset() {
	*x = VPNEvent{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNEvent) ProtoMessage() {}

func (x *VPNEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNEvent.ProtoReflect.Descriptor instead.
func (*VPNEvent) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{12}
}

func (x *VPNEvent) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *VPNEvent) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *VPNEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VPNEvent) GetProvider() VpnProvider {
	if x != nil {
		return x.Provider
	}
	return VpnProvider_VPN_PROVIDER_UNSPECIFIED
}

func (x *VPNEvent) GetPayload() isVPNEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VPNEvent) GetTunnel() *TunnelStateChanged {
	if x != nil {
		if x, ok := x.Payload.(*VPNEvent_Tunnel); ok {
			return x.Tunnel
		}
	}
	return nil
}

func (x *VPNEvent) GetProviderEvent() *ProviderNotification {
	if x != nil {
		if x, ok := x.Payload.(*VPNEvent_ProviderEvent); ok {
			return x.ProviderEvent
		}
	}
	return nil
}

type isVPNEvent_Payload interface {
	isVPNEvent_Payload()
}

type VPNEvent_Tunnel struct {
	Tunnel *TunnelStateChanged `protobuf:"bytes,5,opt,name=tunnel,proto3,oneof"`
}

type VPNEvent_ProviderEvent struct {
	ProviderEvent *ProviderNotification `protobuf:"bytes,6,opt,name=provider_event,json=providerEvent,proto3,oneof"`
}

func (*VPNEvent_Tunnel) isVPNEvent_Payload() {}

func (*VPNEvent_ProviderEvent) isVPNEvent_Payload() {}

type TunnelStateChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      TunnelState            `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=api.gravity.v26.TunnelState" json:"new_state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelStateChanged) Reset() {
	*x = TunnelStateChanged{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStateChanged) ProtoMessage() {}

func (x *TunnelStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStateChanged.ProtoReflect.Descriptor instead.
func (*TunnelStateChanged) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{13}
}

func (x *TunnelStateChanged) GetNewState() TunnelState {
	if x != nil {
		return x.NewState
	}
	return TunnelState_TUNNEL_STATE_UNSPECIFIED
}

func (x *TunnelStateChanged) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProviderNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"` // JSON-encoded provider-specific data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNotification) Reset() {
	*x = ProviderNotification{}
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNotification) ProtoMessage() {}

func (x *ProviderNotification) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_service_v26_vpn_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNotification.ProtoReflect.Descriptor instead.
func (*ProviderNotification) Descriptor() ([]byte, []int) {
	return file_vpn_service_v26_vpn_service_proto_rawDescGZIP(), []int{14}
}

func (x *ProviderNotification) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderNotification) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_vpn_service_v26_vpn_service_proto protoreflect.FileDescriptor

const file_vpn_service_v26_vpn_service_proto_rawDesc = "" +
	"\n" +
	"!vpn_service/v26/vpn_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"\xeb\x01\n" +
	"\n" +
	"VpnProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x128\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1c.api.gravity.v26.VpnProviderR\bprovider\x12\x1f\n" +
	"\vconfig_data\x18\x04 \x01(\fR\n" +
	"configData\x12!\n" +
	"\fauto_connect\x18\x05 \x01(\bR\vautoConnect\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x06 \x01(\tR\tsecretRef\"\xbf\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x128\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1c.api.gravity.v26.VpnProviderR\bprovider\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.api.gravity.v26.TunnelStateR\x05state\x12%\n" +
	"\x0einterface_name\x18\x05 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\a \x01(\x04R\atxBytes\x12+\n" +
	"\x12started_at_unix_ms\x18\b \x01(\x03R\x0fstartedAtUnixMs\"2\n" +
	"\x11VpnProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"|\n" +
	"\x13ApplyProfileRequest\x125\n" +
	"\aprofile\x18\x01 \x01(\v2\x1b.api.gravity.v26.VpnProfileR\aprofile\x12.\n" +
	"\x13connect_after_apply\x18\x02 \x01(\bR\x11connectAfterApply\"3\n" +
	"\x12WatchEventsRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"_\n" +
	"\x0fVpnCapabilities\x12\x1c\n" +
	"\twireguard\x18\x01 \x01(\bR\twireguard\x12\x18\n" +
	"\aopenvpn\x18\x02 \x01(\bR\aopenvpn\x12\x14\n" +
	"\x05ipsec\x18\x03 \x01(\bR\x05ipsec\"\x93\x01\n" +
	"\x17VpnCapabilitiesResponse\x12D\n" +
	"\fcapabilities\x18\x01 \x01(\v2 .api.gravity.v26.VpnCapabilitiesR\fcapabilities\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\x82\x01\n" +
	"\x13VpnProfilesResponse\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.api.gravity.v26.VpnProfileR\bprofiles\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"v\n" +
	"\x14ApplyProfileResponse\x12*\n" +
	"\x11active_profile_id\x18\x01 \x01(\tR\x0factiveProfileId\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"d\n" +
	"\x0fConnectResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"|\n" +
	"\x10SessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.api.gravity.v26.SessionR\bsessions\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\xa6\x01\n" +
	"\x11GetStatusResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.api.gravity.v26.SessionR\asession\x12)\n" +
	"\x10provider_details\x18\x02 \x01(\tR\x0fproviderDetails\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\xba\x02\n" +
	"\bVPNEvent\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x128\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x1c.api.gravity.v26.VpnProviderR\bprovider\x12=\n" +
	"\x06tunnel\x18\x05 \x01(\v2#.api.gravity.v26.TunnelStateChangedH\x00R\x06tunnel\x12N\n" +
	"\x0eprovider_event\x18\x06 \x01(\v2%.api.gravity.v26.ProviderNotificationH\x00R\rproviderEventB\t\n" +
	"\apayload\"i\n" +
	"\x12TunnelStateChanged\x129\n" +
	"\tnew_state\x18\x01 \x01(\x0e2\x1c.api.gravity.v26.TunnelStateR\bnewState\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x14ProviderNotification\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails*\x92\x01\n" +
	"\vVpnProvider\x12\x1c\n" +
	"\x18VPN_PROVIDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VPN_PROVIDER_WIREGUARD\x10\x01\x12\x18\n" +
	"\x14VPN_PROVIDER_OPENVPN\x10\x02\x12\x16\n" +
	"\x12VPN_PROVIDER_IPSEC\x10\x03\x12\x17\n" +
	"\x13VPN_PROVIDER_CUSTOM\x10\x0f*\xa7\x01\n" +
	"\vTunnelState\x12\x1c\n" +
	"\x18TUNNEL_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TUNNEL_STATE_DOWN\x10\x01\x12\x1b\n" +
	"\x17TUNNEL_STATE_CONNECTING\x10\x02\x12\x13\n" +
	"\x0fTUNNEL_STATE_UP\x10\x03\x12\x19\n" +
	"\x15TUNNEL_STATE_DEGRADED\x10\x04\x12\x16\n" +
	"\x12TUNNEL_STATE_ERROR\x10\x052\xf9\x05\n" +
	"\n" +
	"VPNService\x12U\n" +
	"\x0fGetCapabilities\x12\x18.api.gravity.types.Empty\x1a(.api.gravity.v26.VpnCapabilitiesResponse\x12N\n" +
	"\fListProfiles\x12\x18.api.gravity.types.Empty\x1a$.api.gravity.v26.VpnProfilesResponse\x12[\n" +
	"\fApplyProfile\x12$.api.gravity.v26.ApplyProfileRequest\x1a%.api.gravity.v26.ApplyProfileResponse\x12W\n" +
	"\rRemoveProfile\x12\".api.gravity.v26.VpnProfileRequest\x1a\".api.gravity.types.BooleanResponse\x12O\n" +
	"\aConnect\x12\".api.gravity.v26.VpnProfileRequest\x1a .api.gravity.v26.ConnectResponse\x12T\n" +
	"\n" +
	"Disconnect\x12\".api.gravity.v26.VpnProfileRequest\x1a\".api.gravity.types.BooleanResponse\x12I\n" +
	"\tGetStatus\x12\x18.api.gravity.types.Empty\x1a\".api.gravity.v26.GetStatusResponse\x12K\n" +
	"\fListSessions\x12\x18.api.gravity.types.Empty\x1a!.api.gravity.v26.SessionsResponse\x12O\n" +
	"\vWatchEvents\x12#.api.gravity.v26.WatchEventsRequest\x1a\x19.api.gravity.v26.VPNEvent0\x01b\x06proto3"

var (
	file_vpn_service_v26_vpn_service_proto_rawDescOnce sync.Once
	file_vpn_service_v26_vpn_service_proto_rawDescData []byte
)

func file_vpn_service_v26_vpn_service_proto_rawDescGZIP() []byte {
	file_vpn_service_v26_vpn_service_proto_rawDescOnce.Do(func() {
		file_vpn_service_v26_vpn_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_service_v26_vpn_service_proto_rawDesc), len(file_vpn_service_v26_vpn_service_proto_rawDesc)))
	})
	return file_vpn_service_v26_vpn_service_proto_rawDescData
}

var file_vpn_service_v26_vpn_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vpn_service_v26_vpn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_vpn_service_v26_vpn_service_proto_goTypes = []any{
	(VpnProvider)(0),                // 0: api.gravity.v26.VpnProvider
	(TunnelState)(0),                // 1: api.gravity.v26.TunnelState
	(*VpnProfile)(nil),              // 2: api.gravity.v26.VpnProfile
	(*Session)(nil),                 // 3: api.gravity.v26.Session
	(*VpnProfileRequest)(nil),       // 4: api.gravity.v26.VpnProfileRequest
	(*ApplyProfileRequest)(nil),     // 5: api.gravity.v26.ApplyProfileRequest
	(*WatchEventsRequest)(nil),      // 6: api.gravity.v26.WatchEventsRequest
	(*VpnCapabilities)(nil),         // 7: api.gravity.v26.VpnCapabilities
	(*VpnCapabilitiesResponse)(nil), // 8: api.gravity.v26.VpnCapabilitiesResponse
	(*VpnProfilesResponse)(nil),     // 9: api.gravity.v26.VpnProfilesResponse
	(*ApplyProfileResponse)(nil),    // 10: api.gravity.v26.ApplyProfileResponse
	(*ConnectResponse)(nil),         // 11: api.gravity.v26.ConnectResponse
	(*SessionsResponse)(nil),        // 12: api.gravity.v26.SessionsResponse
	(*GetStatusResponse)(nil),       // 13: api.gravity.v26.GetStatusResponse
	(*VPNEvent)(nil),                // 14: api.gravity.v26.VPNEvent
	(*TunnelStateChanged)(nil),      // 15: api.gravity.v26.TunnelStateChanged
	(*ProviderNotification)(nil),    // 16: api.gravity.v26.ProviderNotification
	(*common.ErrorInfo)(nil),        // 17: api.gravity.types.ErrorInfo
	(*common.Empty)(nil),            // 18: api.gravity.types.Empty
	(*common.BooleanResponse)(nil),  // 19: api.gravity.types.BooleanResponse
}
var file_vpn_service_v26_vpn_service_proto_depIdxs = []int32{
	0,  // 0: api.gravity.v26.VpnProfile.provider:type_name -> api.gravity.v26.VpnProvider
	0,  // 1: api.gravity.v26.Session.provider:type_name -> api.gravity.v26.VpnProvider
	1,  // 2: api.gravity.v26.Session.state:type_name -> api.gravity.v26.TunnelState
	2,  // 3: api.gravity.v26.ApplyProfileRequest.profile:type_name -> api.gravity.v26.VpnProfile
	7,  // 4: api.gravity.v26.VpnCapabilitiesResponse.capabilities:type_name -> api.gravity.v26.VpnCapabilities
	17, // 5: api.gravity.v26.VpnCapabilitiesResponse.error:type_name -> api.gravity.types.ErrorInfo
	2,  // 6: api.gravity.v26.VpnProfilesResponse.profiles:type_name -> api.gravity.v26.VpnProfile
	17, // 7: api.gravity.v26.VpnProfilesResponse.error:type_name -> api.gravity.types.ErrorInfo
	17, // 8: api.gravity.v26.ApplyProfileResponse.error:type_name -> api.gravity.types.ErrorInfo
	17, // 9: api.gravity.v26.ConnectResponse.error:type_name -> api.gravity.types.ErrorInfo
	3,  // 10: api.gravity.v26.SessionsResponse.sessions:type_name -> api.gravity.v26.Session
	17, // 11: api.gravity.v26.SessionsResponse.error:type_name -> api.gravity.types.ErrorInfo
	3,  // 12: api.gravity.v26.GetStatusResponse.session:type_name -> api.gravity.v26.Session
	17, // 13: api.gravity.v26.GetStatusResponse.error:type_name -> api.gravity.types.ErrorInfo
	0,  // 14: api.gravity.v26.VPNEvent.provider:type_name -> api.gravity.v26.VpnProvider
	15, // 15: api.gravity.v26.VPNEvent.tunnel:type_name -> api.gravity.v26.TunnelStateChanged
	16, // 16: api.gravity.v26.VPNEvent.provider_event:type_name -> api.gravity.v26.ProviderNotification
	1,  // 17: api.gravity.v26.TunnelStateChanged.new_state:type_name -> api.gravity.v26.TunnelState
	18, // 18: api.gravity.v26.VPNService.GetCapabilities:input_type -> api.gravity.types.Empty
	18, // 19: api.gravity.v26.VPNService.ListProfiles:input_type -> api.gravity.types.Empty
	5,  // 20: api.gravity.v26.VPNService.ApplyProfile:input_type -> api.gravity.v26.ApplyProfileRequest
	4,  // 21: api.gravity.v26.VPNService.RemoveProfile:input_type -> api.gravity.v26.VpnProfileRequest
	4,  // 22: api.gravity.v26.VPNService.Connect:input_type -> api.gravity.v26.VpnProfileRequest
	4,  // 23: api.gravity.v26.VPNService.Disconnect:input_type -> api.gravity.v26.VpnProfileRequest
	18, // 24: api.gravity.v26.VPNService.GetStatus:input_type -> api.gravity.types.Empty
	18, // 25: api.gravity.v26.VPNService.ListSessions:input_type -> api.gravity.types.Empty
	6,  // 26: api.gravity.v26.VPNService.WatchEvents:input_type -> api.gravity.v26.WatchEventsRequest
	8,  // 27: api.gravity.v26.VPNService.GetCapabilities:output_type -> api.gravity.v26.VpnCapabilitiesResponse
	9,  // 28: api.gravity.v26.VPNService.ListProfiles:output_type -> api.gravity.v26.VpnProfilesResponse
	10, // 29: api.gravity.v26.VPNService.ApplyProfile:output_type -> api.gravity.v26.ApplyProfileResponse
	19, // 30: api.gravity.v26.VPNService.RemoveProfile:output_type -> api.gravity.types.BooleanResponse
	11, // 31: api.gravity.v26.VPNService.Connect:output_type -> api.gravity.v26.ConnectResponse
	19, // 32: api.gravity.v26.VPNService.Disconnect:output_type -> api.gravity.types.BooleanResponse
	13, // 33: api.gravity.v26.VPNService.GetStatus:output_type -> api.gravity.v26.GetStatusResponse
	12, // 34: api.gravity.v26.VPNService.ListSessions:output_type -> api.gravity.v26.SessionsResponse
	14, // 35: api.gravity.v26.VPNService.WatchEvents:output_type -> api.gravity.v26.VPNEvent
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_vpn_service_v26_vpn_service_proto_init() }
func file_vpn_service_v26_vpn_service_proto_init() {
	if File_vpn_service_v26_vpn_service_proto != nil {
		return
	}
	file_vpn_service_v26_vpn_service_proto_msgTypes[12].OneofWrappers = []any{
		(*VPNEvent_Tunnel)(nil),
		(*VPNEvent_ProviderEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_service_v26_vpn_service_proto_rawDesc), len(file_vpn_service_v26_vpn_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpn_service_v26_vpn_service_proto_goTypes,
		DependencyIndexes: file_vpn_service_v26_vpn_service_proto_depIdxs,
		EnumInfos:         file_vpn_service_v26_vpn_service_proto_enumTypes,
		MessageInfos:      file_vpn_service_v26_vpn_service_proto_msgTypes,
	}.Build()
	File_vpn_service_v26_vpn_service_proto = out.File
	file_vpn_service_v26_vpn_service_proto_goTypes = nil
	file_vpn_service_v26_vpn_service_proto_depIdxs = nil
}
