// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: spi_service/v26/spi_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpiService_ListSpiBuses_FullMethodName = "/api.gravity.v26.SpiService/ListSpiBuses"
	SpiService_GetSpiConfig_FullMethodName = "/api.gravity.v26.SpiService/GetSpiConfig"
	SpiService_SetSpiConfig_FullMethodName = "/api.gravity.v26.SpiService/SetSpiConfig"
	SpiService_SpiTransfer_FullMethodName  = "/api.gravity.v26.SpiService/SpiTransfer"
)

// SpiServiceClient is the client API for SpiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiServiceClient interface {
	// SPI
	ListSpiBuses(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListSpiBusesResponse, error)
	GetSpiConfig(ctx context.Context, in *SpiBusRequest, opts ...grpc.CallOption) (*SpiConfigResponse, error)
	SetSpiConfig(ctx context.Context, in *SpiConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	SpiTransfer(ctx context.Context, in *SpiTransferRequest, opts ...grpc.CallOption) (*SpiTransferResponse, error)
}

type spiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiServiceClient(cc grpc.ClientConnInterface) SpiServiceClient {
	return &spiServiceClient{cc}
}

func (c *spiServiceClient) ListSpiBuses(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListSpiBusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpiBusesResponse)
	err := c.cc.Invoke(ctx, SpiService_ListSpiBuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiServiceClient) GetSpiConfig(ctx context.Context, in *SpiBusRequest, opts ...grpc.CallOption) (*SpiConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpiConfigResponse)
	err := c.cc.Invoke(ctx, SpiService_GetSpiConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiServiceClient) SetSpiConfig(ctx context.Context, in *SpiConfigRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, SpiService_SetSpiConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiServiceClient) SpiTransfer(ctx context.Context, in *SpiTransferRequest, opts ...grpc.CallOption) (*SpiTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpiTransferResponse)
	err := c.cc.Invoke(ctx, SpiService_SpiTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiServiceServer is the server API for SpiService service.
// All implementations must embed UnimplementedSpiServiceServer
// for forward compatibility.
type SpiServiceServer interface {
	// SPI
	ListSpiBuses(context.Context, *common.Void) (*ListSpiBusesResponse, error)
	GetSpiConfig(context.Context, *SpiBusRequest) (*SpiConfigResponse, error)
	SetSpiConfig(context.Context, *SpiConfigRequest) (*common.BooleanResponse, error)
	SpiTransfer(context.Context, *SpiTransferRequest) (*SpiTransferResponse, error)
	mustEmbedUnimplementedSpiServiceServer()
}

// UnimplementedSpiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpiServiceServer struct{}

func (UnimplementedSpiServiceServer) ListSpiBuses(context.Context, *common.Void) (*ListSpiBusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpiBuses not implemented")
}
func (UnimplementedSpiServiceServer) GetSpiConfig(context.Context, *SpiBusRequest) (*SpiConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpiConfig not implemented")
}
func (UnimplementedSpiServiceServer) SetSpiConfig(context.Context, *SpiConfigRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpiConfig not implemented")
}
func (UnimplementedSpiServiceServer) SpiTransfer(context.Context, *SpiTransferRequest) (*SpiTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpiTransfer not implemented")
}
func (UnimplementedSpiServiceServer) mustEmbedUnimplementedSpiServiceServer() {}
func (UnimplementedSpiServiceServer) testEmbeddedByValue()                    {}

// UnsafeSpiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiServiceServer will
// result in compilation errors.
type UnsafeSpiServiceServer interface {
	mustEmbedUnimplementedSpiServiceServer()
}

func RegisterSpiServiceServer(s grpc.ServiceRegistrar, srv SpiServiceServer) {
	// If the following call panics, it indicates UnimplementedSpiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpiService_ServiceDesc, srv)
}

func _SpiService_ListSpiBuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiServiceServer).ListSpiBuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiService_ListSpiBuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiServiceServer).ListSpiBuses(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiService_GetSpiConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiBusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiServiceServer).GetSpiConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiService_GetSpiConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiServiceServer).GetSpiConfig(ctx, req.(*SpiBusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiService_SetSpiConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiServiceServer).SetSpiConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiService_SetSpiConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiServiceServer).SetSpiConfig(ctx, req.(*SpiConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiService_SpiTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiServiceServer).SpiTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiService_SpiTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiServiceServer).SpiTransfer(ctx, req.(*SpiTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpiService_ServiceDesc is the grpc.ServiceDesc for SpiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.SpiService",
	HandlerType: (*SpiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpiBuses",
			Handler:    _SpiService_ListSpiBuses_Handler,
		},
		{
			MethodName: "GetSpiConfig",
			Handler:    _SpiService_GetSpiConfig_Handler,
		},
		{
			MethodName: "SetSpiConfig",
			Handler:    _SpiService_SetSpiConfig_Handler,
		},
		{
			MethodName: "SpiTransfer",
			Handler:    _SpiService_SpiTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spi_service/v26/spi_service.proto",
}
