// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: sensor_service/v26/sensor_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorService_GetCapabilities_FullMethodName       = "/api.gravity.v26.SensorService/GetCapabilities"
	SensorService_SubscribeSensorEvents_FullMethodName = "/api.gravity.v26.SensorService/SubscribeSensorEvents"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SensorService definition
type SensorServiceClient interface {
	// Returns available sensor capabilities in the system
	GetCapabilities(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Subscribes to sensor events (stream)
	SubscribeSensorEvents(ctx context.Context, in *SensorEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorEventResponse], error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) GetCapabilities(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, SensorService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) SubscribeSensorEvents(ctx context.Context, in *SensorEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], SensorService_SubscribeSensorEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensorEventsRequest, SensorEventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_SubscribeSensorEventsClient = grpc.ServerStreamingClient[SensorEventResponse]

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility.
//
// SensorService definition
type SensorServiceServer interface {
	// Returns available sensor capabilities in the system
	GetCapabilities(context.Context, *common.Empty) (*CapabilitiesResponse, error)
	// Subscribes to sensor events (stream)
	SubscribeSensorEvents(*SensorEventsRequest, grpc.ServerStreamingServer[SensorEventResponse]) error
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServiceServer struct{}

func (UnimplementedSensorServiceServer) GetCapabilities(context.Context, *common.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSensorServiceServer) SubscribeSensorEvents(*SensorEventsRequest, grpc.ServerStreamingServer[SensorEventResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSensorEvents not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}
func (UnimplementedSensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	// If the following call panics, it indicates UnimplementedSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).GetCapabilities(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_SubscribeSensorEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SensorEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorServiceServer).SubscribeSensorEvents(m, &grpc.GenericServerStream[SensorEventsRequest, SensorEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_SubscribeSensorEventsServer = grpc.ServerStreamingServer[SensorEventResponse]

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _SensorService_GetCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeSensorEvents",
			Handler:       _SensorService_SubscribeSensorEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sensor_service/v26/sensor_service.proto",
}
