// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sensor_service/v26/sensor_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response for GetCapabilities
type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])
	SensorTypes   []string          `protobuf:"bytes,1,rep,name=sensor_types,json=sensorTypes,proto3" json:"sensor_types,omitempty"`
	Error         *common.ErrorInfo `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_sensor_service_v26_sensor_service_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilitiesResponse) GetSensorTypes() []string {
	if x != nil {
		return x.SensorTypes
	}
	return nil
}

func (x *CapabilitiesResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// Request for SubscribeSensorEvents
type SensorEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by sensor type (empty = all)
	// Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
	SensorTypes   []string `protobuf:"bytes,1,rep,name=sensor_types,json=sensorTypes,proto3" json:"sensor_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorEventsRequest) Reset() {
	*x = SensorEventsRequest{}
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEventsRequest) ProtoMessage() {}

func (x *SensorEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEventsRequest.ProtoReflect.Descriptor instead.
func (*SensorEventsRequest) Descriptor() ([]byte, []int) {
	return file_sensor_service_v26_sensor_service_proto_rawDescGZIP(), []int{1}
}

func (x *SensorEventsRequest) GetSensorTypes() []string {
	if x != nil {
		return x.SensorTypes
	}
	return nil
}

// Response for sensor events
type SensorEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *SensorEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorEventResponse) Reset() {
	*x = SensorEventResponse{}
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEventResponse) ProtoMessage() {}

func (x *SensorEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEventResponse.ProtoReflect.Descriptor instead.
func (*SensorEventResponse) Descriptor() ([]byte, []int) {
	return file_sensor_service_v26_sensor_service_proto_rawDescGZIP(), []int{2}
}

func (x *SensorEventResponse) GetEvent() *SensorEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SensorEventResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// Sensor event
type SensorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event timestamp (Unix timestamp in milliseconds)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")
	SensorType string `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	// Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")
	SensorName string `protobuf:"bytes,3,opt,name=sensor_name,json=sensorName,proto3" json:"sensor_name,omitempty"`
	// Array of sensor values (generic)
	// Examples:
	// - Temperature: [45.2]
	// - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
	// - Multiple temperatures: [45.2, 50.1, 48.3]
	Values []float64 `protobuf:"fixed64,4,rep,packed,name=values,proto3" json:"values,omitempty"`
	// Metadata describing how to interpret the values
	// Examples:
	// - Temperature: {"format": "[ºC]", "unit": "celsius"}
	// - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
	// - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
	// - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorEvent) Reset() {
	*x = SensorEvent{}
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEvent) ProtoMessage() {}

func (x *SensorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_service_v26_sensor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEvent.ProtoReflect.Descriptor instead.
func (*SensorEvent) Descriptor() ([]byte, []int) {
	return file_sensor_service_v26_sensor_service_proto_rawDescGZIP(), []int{3}
}

func (x *SensorEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorEvent) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorEvent) GetSensorName() string {
	if x != nil {
		return x.SensorName
	}
	return ""
}

func (x *SensorEvent) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SensorEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sensor_service_v26_sensor_service_proto protoreflect.FileDescriptor

const file_sensor_service_v26_sensor_service_proto_rawDesc = "" +
	"\n" +
	"'sensor_service/v26/sensor_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"m\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fsensor_types\x18\x01 \x03(\tR\vsensorTypes\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"8\n" +
	"\x13SensorEventsRequest\x12!\n" +
	"\fsensor_types\x18\x01 \x03(\tR\vsensorTypes\"}\n" +
	"\x13SensorEventResponse\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.api.gravity.v26.SensorEventR\x05event\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\x8a\x02\n" +
	"\vSensorEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x1f\n" +
	"\vsensor_name\x18\x03 \x01(\tR\n" +
	"sensorName\x12\x16\n" +
	"\x06values\x18\x04 \x03(\x01R\x06values\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.api.gravity.v26.SensorEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xca\x01\n" +
	"\rSensorService\x12R\n" +
	"\x0fGetCapabilities\x12\x18.api.gravity.types.Empty\x1a%.api.gravity.v26.CapabilitiesResponse\x12e\n" +
	"\x15SubscribeSensorEvents\x12$.api.gravity.v26.SensorEventsRequest\x1a$.api.gravity.v26.SensorEventResponse0\x01b\x06proto3"

var (
	file_sensor_service_v26_sensor_service_proto_rawDescOnce sync.Once
	file_sensor_service_v26_sensor_service_proto_rawDescData []byte
)

func file_sensor_service_v26_sensor_service_proto_rawDescGZIP() []byte {
	file_sensor_service_v26_sensor_service_proto_rawDescOnce.Do(func() {
		file_sensor_service_v26_sensor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_service_v26_sensor_service_proto_rawDesc), len(file_sensor_service_v26_sensor_service_proto_rawDesc)))
	})
	return file_sensor_service_v26_sensor_service_proto_rawDescData
}

var file_sensor_service_v26_sensor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sensor_service_v26_sensor_service_proto_goTypes = []any{
	(*CapabilitiesResponse)(nil), // 0: api.gravity.v26.CapabilitiesResponse
	(*SensorEventsRequest)(nil),  // 1: api.gravity.v26.SensorEventsRequest
	(*SensorEventResponse)(nil),  // 2: api.gravity.v26.SensorEventResponse
	(*SensorEvent)(nil),          // 3: api.gravity.v26.SensorEvent
	nil,                          // 4: api.gravity.v26.SensorEvent.MetadataEntry
	(*common.ErrorInfo)(nil),     // 5: api.gravity.types.ErrorInfo
	(*common.Empty)(nil),         // 6: api.gravity.types.Empty
}
var file_sensor_service_v26_sensor_service_proto_depIdxs = []int32{
	5, // 0: api.gravity.v26.CapabilitiesResponse.error:type_name -> api.gravity.types.ErrorInfo
	3, // 1: api.gravity.v26.SensorEventResponse.event:type_name -> api.gravity.v26.SensorEvent
	5, // 2: api.gravity.v26.SensorEventResponse.error:type_name -> api.gravity.types.ErrorInfo
	4, // 3: api.gravity.v26.SensorEvent.metadata:type_name -> api.gravity.v26.SensorEvent.MetadataEntry
	6, // 4: api.gravity.v26.SensorService.GetCapabilities:input_type -> api.gravity.types.Empty
	1, // 5: api.gravity.v26.SensorService.SubscribeSensorEvents:input_type -> api.gravity.v26.SensorEventsRequest
	0, // 6: api.gravity.v26.SensorService.GetCapabilities:output_type -> api.gravity.v26.CapabilitiesResponse
	2, // 7: api.gravity.v26.SensorService.SubscribeSensorEvents:output_type -> api.gravity.v26.SensorEventResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sensor_service_v26_sensor_service_proto_init() }
func file_sensor_service_v26_sensor_service_proto_init() {
	if File_sensor_service_v26_sensor_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_service_v26_sensor_service_proto_rawDesc), len(file_sensor_service_v26_sensor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_service_v26_sensor_service_proto_goTypes,
		DependencyIndexes: file_sensor_service_v26_sensor_service_proto_depIdxs,
		MessageInfos:      file_sensor_service_v26_sensor_service_proto_msgTypes,
	}.Build()
	File_sensor_service_v26_sensor_service_proto = out.File
	file_sensor_service_v26_sensor_service_proto_goTypes = nil
	file_sensor_service_v26_sensor_service_proto_depIdxs = nil
}
