// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: gpio_service/v26/gpio_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GpioService_ListGPIOPins_FullMethodName     = "/api.gravity.v26.GpioService/ListGPIOPins"
	GpioService_GetGPIOLevel_FullMethodName     = "/api.gravity.v26.GpioService/GetGPIOLevel"
	GpioService_SetGPIOLevel_FullMethodName     = "/api.gravity.v26.GpioService/SetGPIOLevel"
	GpioService_GetGPIODirection_FullMethodName = "/api.gravity.v26.GpioService/GetGPIODirection"
	GpioService_SetGPIODirection_FullMethodName = "/api.gravity.v26.GpioService/SetGPIODirection"
)

// GpioServiceClient is the client API for GpioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GpioServiceClient interface {
	// GPIO
	ListGPIOPins(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListGpioPinsResponse, error)
	GetGPIOLevel(ctx context.Context, in *GpioLevelRequest, opts ...grpc.CallOption) (*GpioLevelResponse, error)
	SetGPIOLevel(ctx context.Context, in *GpioLevelRequest, opts ...grpc.CallOption) (*GpioLevelResponse, error)
	GetGPIODirection(ctx context.Context, in *GpioDirectionRequest, opts ...grpc.CallOption) (*GpioDirectionResponse, error)
	SetGPIODirection(ctx context.Context, in *GpioDirectionRequest, opts ...grpc.CallOption) (*GpioDirectionResponse, error)
}

type gpioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGpioServiceClient(cc grpc.ClientConnInterface) GpioServiceClient {
	return &gpioServiceClient{cc}
}

func (c *gpioServiceClient) ListGPIOPins(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*ListGpioPinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGpioPinsResponse)
	err := c.cc.Invoke(ctx, GpioService_ListGPIOPins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpioServiceClient) GetGPIOLevel(ctx context.Context, in *GpioLevelRequest, opts ...grpc.CallOption) (*GpioLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpioLevelResponse)
	err := c.cc.Invoke(ctx, GpioService_GetGPIOLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpioServiceClient) SetGPIOLevel(ctx context.Context, in *GpioLevelRequest, opts ...grpc.CallOption) (*GpioLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpioLevelResponse)
	err := c.cc.Invoke(ctx, GpioService_SetGPIOLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpioServiceClient) GetGPIODirection(ctx context.Context, in *GpioDirectionRequest, opts ...grpc.CallOption) (*GpioDirectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpioDirectionResponse)
	err := c.cc.Invoke(ctx, GpioService_GetGPIODirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpioServiceClient) SetGPIODirection(ctx context.Context, in *GpioDirectionRequest, opts ...grpc.CallOption) (*GpioDirectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpioDirectionResponse)
	err := c.cc.Invoke(ctx, GpioService_SetGPIODirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GpioServiceServer is the server API for GpioService service.
// All implementations must embed UnimplementedGpioServiceServer
// for forward compatibility.
type GpioServiceServer interface {
	// GPIO
	ListGPIOPins(context.Context, *common.Void) (*ListGpioPinsResponse, error)
	GetGPIOLevel(context.Context, *GpioLevelRequest) (*GpioLevelResponse, error)
	SetGPIOLevel(context.Context, *GpioLevelRequest) (*GpioLevelResponse, error)
	GetGPIODirection(context.Context, *GpioDirectionRequest) (*GpioDirectionResponse, error)
	SetGPIODirection(context.Context, *GpioDirectionRequest) (*GpioDirectionResponse, error)
	mustEmbedUnimplementedGpioServiceServer()
}

// UnimplementedGpioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGpioServiceServer struct{}

func (UnimplementedGpioServiceServer) ListGPIOPins(context.Context, *common.Void) (*ListGpioPinsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGPIOPins not implemented")
}
func (UnimplementedGpioServiceServer) GetGPIOLevel(context.Context, *GpioLevelRequest) (*GpioLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPIOLevel not implemented")
}
func (UnimplementedGpioServiceServer) SetGPIOLevel(context.Context, *GpioLevelRequest) (*GpioLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGPIOLevel not implemented")
}
func (UnimplementedGpioServiceServer) GetGPIODirection(context.Context, *GpioDirectionRequest) (*GpioDirectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPIODirection not implemented")
}
func (UnimplementedGpioServiceServer) SetGPIODirection(context.Context, *GpioDirectionRequest) (*GpioDirectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGPIODirection not implemented")
}
func (UnimplementedGpioServiceServer) mustEmbedUnimplementedGpioServiceServer() {}
func (UnimplementedGpioServiceServer) testEmbeddedByValue()                     {}

// UnsafeGpioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GpioServiceServer will
// result in compilation errors.
type UnsafeGpioServiceServer interface {
	mustEmbedUnimplementedGpioServiceServer()
}

func RegisterGpioServiceServer(s grpc.ServiceRegistrar, srv GpioServiceServer) {
	// If the following call panics, it indicates UnimplementedGpioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GpioService_ServiceDesc, srv)
}

func _GpioService_ListGPIOPins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpioServiceServer).ListGPIOPins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpioService_ListGPIOPins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpioServiceServer).ListGPIOPins(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpioService_GetGPIOLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpioLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpioServiceServer).GetGPIOLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpioService_GetGPIOLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpioServiceServer).GetGPIOLevel(ctx, req.(*GpioLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpioService_SetGPIOLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpioLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpioServiceServer).SetGPIOLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpioService_SetGPIOLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpioServiceServer).SetGPIOLevel(ctx, req.(*GpioLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpioService_GetGPIODirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpioDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpioServiceServer).GetGPIODirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpioService_GetGPIODirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpioServiceServer).GetGPIODirection(ctx, req.(*GpioDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GpioService_SetGPIODirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpioDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpioServiceServer).SetGPIODirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GpioService_SetGPIODirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpioServiceServer).SetGPIODirection(ctx, req.(*GpioDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GpioService_ServiceDesc is the grpc.ServiceDesc for GpioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GpioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.GpioService",
	HandlerType: (*GpioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGPIOPins",
			Handler:    _GpioService_ListGPIOPins_Handler,
		},
		{
			MethodName: "GetGPIOLevel",
			Handler:    _GpioService_GetGPIOLevel_Handler,
		},
		{
			MethodName: "SetGPIOLevel",
			Handler:    _GpioService_SetGPIOLevel_Handler,
		},
		{
			MethodName: "GetGPIODirection",
			Handler:    _GpioService_GetGPIODirection_Handler,
		},
		{
			MethodName: "SetGPIODirection",
			Handler:    _GpioService_SetGPIODirection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpio_service/v26/gpio_service.proto",
}
