// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: i2c_service/v26/i2c_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to address a specific I2C bus
type I2CBusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bus           uint32                 `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"` // bus number (e.g., 1 for /dev/i2c-1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CBusRequest) Reset() {
	*x = I2CBusRequest{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CBusRequest) ProtoMessage() {}

func (x *I2CBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CBusRequest.ProtoReflect.Descriptor instead.
func (*I2CBusRequest) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{0}
}

func (x *I2CBusRequest) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

// Generic I2C transfer request.
// Operation is inferred from the fields:
//
//	data only              → write
//	read_length only       → read
//	data + read_length     → write-then-read (combined transaction, repeated START)
//
// Note: register address, if needed, is the first byte(s) of data.
type I2CTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bus           uint32                 `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"`                                 // bus number
	Address       uint32                 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`                         // 7-bit device address (e.g., 0x48)
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                // bytes to write
	ReadLength    uint32                 `protobuf:"varint,4,opt,name=read_length,json=readLength,proto3" json:"read_length,omitempty"` // number of bytes to read
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`                             // optional flags mapped to Linux i2c_msg flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CTransferRequest) Reset() {
	*x = I2CTransferRequest{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CTransferRequest) ProtoMessage() {}

func (x *I2CTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CTransferRequest.ProtoReflect.Descriptor instead.
func (*I2CTransferRequest) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{1}
}

func (x *I2CTransferRequest) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *I2CTransferRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *I2CTransferRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *I2CTransferRequest) GetReadLength() uint32 {
	if x != nil {
		return x.ReadLength
	}
	return 0
}

func (x *I2CTransferRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// I2C bus configuration
type I2CConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bus             uint32                 `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"`                                                // bus number
	ClockHz         uint32                 `protobuf:"varint,2,opt,name=clock_hz,json=clockHz,proto3" json:"clock_hz,omitempty"`                         // clock frequency in Hz (may not be changeable at runtime)
	TenBitAddr      bool                   `protobuf:"varint,3,opt,name=ten_bit_addr,json=tenBitAddr,proto3" json:"ten_bit_addr,omitempty"`              // true = 10-bit addressing, false = 7-bit (default)
	ClockStretching bool                   `protobuf:"varint,4,opt,name=clock_stretching,json=clockStretching,proto3" json:"clock_stretching,omitempty"` // allow slave to hold SCL low to pause transfer
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *I2CConfigRequest) Reset() {
	*x = I2CConfigRequest{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CConfigRequest) ProtoMessage() {}

func (x *I2CConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CConfigRequest.ProtoReflect.Descriptor instead.
func (*I2CConfigRequest) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{2}
}

func (x *I2CConfigRequest) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *I2CConfigRequest) GetClockHz() uint32 {
	if x != nil {
		return x.ClockHz
	}
	return 0
}

func (x *I2CConfigRequest) GetTenBitAddr() bool {
	if x != nil {
		return x.TenBitAddr
	}
	return false
}

func (x *I2CConfigRequest) GetClockStretching() bool {
	if x != nil {
		return x.ClockStretching
	}
	return false
}

type I2CConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bus             uint32                 `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"`
	ClockHz         uint32                 `protobuf:"varint,2,opt,name=clock_hz,json=clockHz,proto3" json:"clock_hz,omitempty"`
	TenBitAddr      bool                   `protobuf:"varint,3,opt,name=ten_bit_addr,json=tenBitAddr,proto3" json:"ten_bit_addr,omitempty"`
	ClockStretching bool                   `protobuf:"varint,4,opt,name=clock_stretching,json=clockStretching,proto3" json:"clock_stretching,omitempty"`
	Error           *common.ErrorInfo      `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *I2CConfigResponse) Reset() {
	*x = I2CConfigResponse{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CConfigResponse) ProtoMessage() {}

func (x *I2CConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CConfigResponse.ProtoReflect.Descriptor instead.
func (*I2CConfigResponse) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{3}
}

func (x *I2CConfigResponse) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *I2CConfigResponse) GetClockHz() uint32 {
	if x != nil {
		return x.ClockHz
	}
	return 0
}

func (x *I2CConfigResponse) GetTenBitAddr() bool {
	if x != nil {
		return x.TenBitAddr
	}
	return false
}

func (x *I2CConfigResponse) GetClockStretching() bool {
	if x != nil {
		return x.ClockStretching
	}
	return false
}

func (x *I2CConfigResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// List of available I2C buses
type I2CBusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buses         []uint32               `protobuf:"varint,1,rep,packed,name=buses,proto3" json:"buses,omitempty"` // e.g., [0, 1, 2]
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CBusesResponse) Reset() {
	*x = I2CBusesResponse{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CBusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CBusesResponse) ProtoMessage() {}

func (x *I2CBusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CBusesResponse.ProtoReflect.Descriptor instead.
func (*I2CBusesResponse) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{4}
}

func (x *I2CBusesResponse) GetBuses() []uint32 {
	if x != nil {
		return x.Buses
	}
	return nil
}

func (x *I2CBusesResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// Addresses found during a bus scan
type I2CScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []uint32               `protobuf:"varint,1,rep,packed,name=addresses,proto3" json:"addresses,omitempty"` // 7-bit addresses (e.g., [0x48, 0x68])
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CScanResponse) Reset() {
	*x = I2CScanResponse{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CScanResponse) ProtoMessage() {}

func (x *I2CScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CScanResponse.ProtoReflect.Descriptor instead.
func (*I2CScanResponse) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{5}
}

func (x *I2CScanResponse) GetAddresses() []uint32 {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *I2CScanResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

// Data returned from a read operation
type I2CReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *common.ErrorInfo      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CReadResponse) Reset() {
	*x = I2CReadResponse{}
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CReadResponse) ProtoMessage() {}

func (x *I2CReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i2c_service_v26_i2c_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CReadResponse.ProtoReflect.Descriptor instead.
func (*I2CReadResponse) Descriptor() ([]byte, []int) {
	return file_i2c_service_v26_i2c_service_proto_rawDescGZIP(), []int{6}
}

func (x *I2CReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *I2CReadResponse) GetError() *common.ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_i2c_service_v26_i2c_service_proto protoreflect.FileDescriptor

const file_i2c_service_v26_i2c_service_proto_rawDesc = "" +
	"\n" +
	"!i2c_service/v26/i2c_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"!\n" +
	"\rI2CBusRequest\x12\x10\n" +
	"\x03bus\x18\x01 \x01(\rR\x03bus\"\x8b\x01\n" +
	"\x12I2CTransferRequest\x12\x10\n" +
	"\x03bus\x18\x01 \x01(\rR\x03bus\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\rR\aaddress\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vread_length\x18\x04 \x01(\rR\n" +
	"readLength\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"\x8c\x01\n" +
	"\x10I2CConfigRequest\x12\x10\n" +
	"\x03bus\x18\x01 \x01(\rR\x03bus\x12\x19\n" +
	"\bclock_hz\x18\x02 \x01(\rR\aclockHz\x12 \n" +
	"\ften_bit_addr\x18\x03 \x01(\bR\n" +
	"tenBitAddr\x12)\n" +
	"\x10clock_stretching\x18\x04 \x01(\bR\x0fclockStretching\"\xc1\x01\n" +
	"\x11I2CConfigResponse\x12\x10\n" +
	"\x03bus\x18\x01 \x01(\rR\x03bus\x12\x19\n" +
	"\bclock_hz\x18\x02 \x01(\rR\aclockHz\x12 \n" +
	"\ften_bit_addr\x18\x03 \x01(\bR\n" +
	"tenBitAddr\x12)\n" +
	"\x10clock_stretching\x18\x04 \x01(\bR\x0fclockStretching\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"\\\n" +
	"\x10I2CBusesResponse\x12\x14\n" +
	"\x05buses\x18\x01 \x03(\rR\x05buses\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"c\n" +
	"\x0fI2CScanResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\rR\taddresses\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error\"Y\n" +
	"\x0fI2CReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.api.gravity.types.ErrorInfoR\x05error2\xa9\x03\n" +
	"\n" +
	"I2CService\x12J\n" +
	"\fListI2CBuses\x12\x17.api.gravity.types.Void\x1a!.api.gravity.v26.I2CBusesResponse\x12N\n" +
	"\n" +
	"ScanI2CBus\x12\x1e.api.gravity.v26.I2CBusRequest\x1a .api.gravity.v26.I2CScanResponse\x12R\n" +
	"\fGetI2CConfig\x12\x1e.api.gravity.v26.I2CBusRequest\x1a\".api.gravity.v26.I2CConfigResponse\x12U\n" +
	"\fSetI2CConfig\x12!.api.gravity.v26.I2CConfigRequest\x1a\".api.gravity.types.BooleanResponse\x12T\n" +
	"\vI2CTransfer\x12#.api.gravity.v26.I2CTransferRequest\x1a .api.gravity.v26.I2CReadResponseb\x06proto3"

var (
	file_i2c_service_v26_i2c_service_proto_rawDescOnce sync.Once
	file_i2c_service_v26_i2c_service_proto_rawDescData []byte
)

func file_i2c_service_v26_i2c_service_proto_rawDescGZIP() []byte {
	file_i2c_service_v26_i2c_service_proto_rawDescOnce.Do(func() {
		file_i2c_service_v26_i2c_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_i2c_service_v26_i2c_service_proto_rawDesc), len(file_i2c_service_v26_i2c_service_proto_rawDesc)))
	})
	return file_i2c_service_v26_i2c_service_proto_rawDescData
}

var file_i2c_service_v26_i2c_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_i2c_service_v26_i2c_service_proto_goTypes = []any{
	(*I2CBusRequest)(nil),          // 0: api.gravity.v26.I2CBusRequest
	(*I2CTransferRequest)(nil),     // 1: api.gravity.v26.I2CTransferRequest
	(*I2CConfigRequest)(nil),       // 2: api.gravity.v26.I2CConfigRequest
	(*I2CConfigResponse)(nil),      // 3: api.gravity.v26.I2CConfigResponse
	(*I2CBusesResponse)(nil),       // 4: api.gravity.v26.I2CBusesResponse
	(*I2CScanResponse)(nil),        // 5: api.gravity.v26.I2CScanResponse
	(*I2CReadResponse)(nil),        // 6: api.gravity.v26.I2CReadResponse
	(*common.ErrorInfo)(nil),       // 7: api.gravity.types.ErrorInfo
	(*common.Void)(nil),            // 8: api.gravity.types.Void
	(*common.BooleanResponse)(nil), // 9: api.gravity.types.BooleanResponse
}
var file_i2c_service_v26_i2c_service_proto_depIdxs = []int32{
	7, // 0: api.gravity.v26.I2CConfigResponse.error:type_name -> api.gravity.types.ErrorInfo
	7, // 1: api.gravity.v26.I2CBusesResponse.error:type_name -> api.gravity.types.ErrorInfo
	7, // 2: api.gravity.v26.I2CScanResponse.error:type_name -> api.gravity.types.ErrorInfo
	7, // 3: api.gravity.v26.I2CReadResponse.error:type_name -> api.gravity.types.ErrorInfo
	8, // 4: api.gravity.v26.I2CService.ListI2CBuses:input_type -> api.gravity.types.Void
	0, // 5: api.gravity.v26.I2CService.ScanI2CBus:input_type -> api.gravity.v26.I2CBusRequest
	0, // 6: api.gravity.v26.I2CService.GetI2CConfig:input_type -> api.gravity.v26.I2CBusRequest
	2, // 7: api.gravity.v26.I2CService.SetI2CConfig:input_type -> api.gravity.v26.I2CConfigRequest
	1, // 8: api.gravity.v26.I2CService.I2CTransfer:input_type -> api.gravity.v26.I2CTransferRequest
	4, // 9: api.gravity.v26.I2CService.ListI2CBuses:output_type -> api.gravity.v26.I2CBusesResponse
	5, // 10: api.gravity.v26.I2CService.ScanI2CBus:output_type -> api.gravity.v26.I2CScanResponse
	3, // 11: api.gravity.v26.I2CService.GetI2CConfig:output_type -> api.gravity.v26.I2CConfigResponse
	9, // 12: api.gravity.v26.I2CService.SetI2CConfig:output_type -> api.gravity.types.BooleanResponse
	6, // 13: api.gravity.v26.I2CService.I2CTransfer:output_type -> api.gravity.v26.I2CReadResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_i2c_service_v26_i2c_service_proto_init() }
func file_i2c_service_v26_i2c_service_proto_init() {
	if File_i2c_service_v26_i2c_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_i2c_service_v26_i2c_service_proto_rawDesc), len(file_i2c_service_v26_i2c_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_i2c_service_v26_i2c_service_proto_goTypes,
		DependencyIndexes: file_i2c_service_v26_i2c_service_proto_depIdxs,
		MessageInfos:      file_i2c_service_v26_i2c_service_proto_msgTypes,
	}.Build()
	File_i2c_service_v26_i2c_service_proto = out.File
	file_i2c_service_v26_i2c_service_proto_goTypes = nil
	file_i2c_service_v26_i2c_service_proto_depIdxs = nil
}
