// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: pwm_service/v26/pwm_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PwmService_ListPwmChannels_FullMethodName  = "/api.gravity.v26.PwmService/ListPwmChannels"
	PwmService_GetPwmProperties_FullMethodName = "/api.gravity.v26.PwmService/GetPwmProperties"
	PwmService_SetPwm_FullMethodName           = "/api.gravity.v26.PwmService/SetPwm"
	PwmService_StopPwm_FullMethodName          = "/api.gravity.v26.PwmService/StopPwm"
)

// PwmServiceClient is the client API for PwmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PwmServiceClient interface {
	// Channel info
	ListPwmChannels(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PwmChannelsResponse, error)
	GetPwmProperties(ctx context.Context, in *PwmChannelRequest, opts ...grpc.CallOption) (*PwmPropertiesResponse, error)
	// Control
	SetPwm(ctx context.Context, in *SetPwmRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
	StopPwm(ctx context.Context, in *PwmChannelRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
}

type pwmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPwmServiceClient(cc grpc.ClientConnInterface) PwmServiceClient {
	return &pwmServiceClient{cc}
}

func (c *pwmServiceClient) ListPwmChannels(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PwmChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PwmChannelsResponse)
	err := c.cc.Invoke(ctx, PwmService_ListPwmChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pwmServiceClient) GetPwmProperties(ctx context.Context, in *PwmChannelRequest, opts ...grpc.CallOption) (*PwmPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PwmPropertiesResponse)
	err := c.cc.Invoke(ctx, PwmService_GetPwmProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pwmServiceClient) SetPwm(ctx context.Context, in *SetPwmRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, PwmService_SetPwm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pwmServiceClient) StopPwm(ctx context.Context, in *PwmChannelRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, PwmService_StopPwm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PwmServiceServer is the server API for PwmService service.
// All implementations must embed UnimplementedPwmServiceServer
// for forward compatibility.
type PwmServiceServer interface {
	// Channel info
	ListPwmChannels(context.Context, *common.Empty) (*PwmChannelsResponse, error)
	GetPwmProperties(context.Context, *PwmChannelRequest) (*PwmPropertiesResponse, error)
	// Control
	SetPwm(context.Context, *SetPwmRequest) (*common.BooleanResponse, error)
	StopPwm(context.Context, *PwmChannelRequest) (*common.BooleanResponse, error)
	mustEmbedUnimplementedPwmServiceServer()
}

// UnimplementedPwmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPwmServiceServer struct{}

func (UnimplementedPwmServiceServer) ListPwmChannels(context.Context, *common.Empty) (*PwmChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPwmChannels not implemented")
}
func (UnimplementedPwmServiceServer) GetPwmProperties(context.Context, *PwmChannelRequest) (*PwmPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPwmProperties not implemented")
}
func (UnimplementedPwmServiceServer) SetPwm(context.Context, *SetPwmRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPwm not implemented")
}
func (UnimplementedPwmServiceServer) StopPwm(context.Context, *PwmChannelRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPwm not implemented")
}
func (UnimplementedPwmServiceServer) mustEmbedUnimplementedPwmServiceServer() {}
func (UnimplementedPwmServiceServer) testEmbeddedByValue()                    {}

// UnsafePwmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PwmServiceServer will
// result in compilation errors.
type UnsafePwmServiceServer interface {
	mustEmbedUnimplementedPwmServiceServer()
}

func RegisterPwmServiceServer(s grpc.ServiceRegistrar, srv PwmServiceServer) {
	// If the following call panics, it indicates UnimplementedPwmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PwmService_ServiceDesc, srv)
}

func _PwmService_ListPwmChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PwmServiceServer).ListPwmChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PwmService_ListPwmChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PwmServiceServer).ListPwmChannels(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PwmService_GetPwmProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PwmChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PwmServiceServer).GetPwmProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PwmService_GetPwmProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PwmServiceServer).GetPwmProperties(ctx, req.(*PwmChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PwmService_SetPwm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPwmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PwmServiceServer).SetPwm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PwmService_SetPwm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PwmServiceServer).SetPwm(ctx, req.(*SetPwmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PwmService_StopPwm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PwmChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PwmServiceServer).StopPwm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PwmService_StopPwm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PwmServiceServer).StopPwm(ctx, req.(*PwmChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PwmService_ServiceDesc is the grpc.ServiceDesc for PwmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PwmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.PwmService",
	HandlerType: (*PwmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPwmChannels",
			Handler:    _PwmService_ListPwmChannels_Handler,
		},
		{
			MethodName: "GetPwmProperties",
			Handler:    _PwmService_GetPwmProperties_Handler,
		},
		{
			MethodName: "SetPwm",
			Handler:    _PwmService_SetPwm_Handler,
		},
		{
			MethodName: "StopPwm",
			Handler:    _PwmService_StopPwm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pwm_service/v26/pwm_service.proto",
}
