// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: power_service/v26/power_service.proto

package v26

import (
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerMode int32

const (
	PowerMode_POWER_MODE_UNSPECIFIED PowerMode = 0
	PowerMode_POWER_MODE_NORMAL      PowerMode = 1
	PowerMode_POWER_MODE_LOW_POWER   PowerMode = 2
	PowerMode_POWER_MODE_PERFORMANCE PowerMode = 3
	PowerMode_POWER_MODE_BALANCED    PowerMode = 4
)

// Enum value maps for PowerMode.
var (
	PowerMode_name = map[int32]string{
		0: "POWER_MODE_UNSPECIFIED",
		1: "POWER_MODE_NORMAL",
		2: "POWER_MODE_LOW_POWER",
		3: "POWER_MODE_PERFORMANCE",
		4: "POWER_MODE_BALANCED",
	}
	PowerMode_value = map[string]int32{
		"POWER_MODE_UNSPECIFIED": 0,
		"POWER_MODE_NORMAL":      1,
		"POWER_MODE_LOW_POWER":   2,
		"POWER_MODE_PERFORMANCE": 3,
		"POWER_MODE_BALANCED":    4,
	}
)

func (x PowerMode) Enum() *PowerMode {
	p := new(PowerMode)
	*p = x
	return p
}

func (x PowerMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerMode) Descriptor() protoreflect.EnumDescriptor {
	return file_power_service_v26_power_service_proto_enumTypes[0].Descriptor()
}

func (PowerMode) Type() protoreflect.EnumType {
	return &file_power_service_v26_power_service_proto_enumTypes[0]
}

func (x PowerMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerMode.Descriptor instead.
func (PowerMode) EnumDescriptor() ([]byte, []int) {
	return file_power_service_v26_power_service_proto_rawDescGZIP(), []int{0}
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`  // If true, forces the reboot immediately
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Reason for the reboot (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_power_service_v26_power_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_service_v26_power_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_power_service_v26_power_service_proto_rawDescGZIP(), []int{0}
}

func (x *RebootRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RebootRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`  // If true, forces the shutdown immediately
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Reason for the shutdown (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_power_service_v26_power_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_power_service_v26_power_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_power_service_v26_power_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_power_service_v26_power_service_proto protoreflect.FileDescriptor

const file_power_service_v26_power_service_proto_rawDesc = "" +
	"\n" +
	"%power_service/v26/power_service.proto\x12\x0fapi.gravity.v26\x1a\x12common/types.proto\"=\n" +
	"\rRebootRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"?\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x8d\x01\n" +
	"\tPowerMode\x12\x1a\n" +
	"\x16POWER_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POWER_MODE_NORMAL\x10\x01\x12\x18\n" +
	"\x14POWER_MODE_LOW_POWER\x10\x02\x12\x1a\n" +
	"\x16POWER_MODE_PERFORMANCE\x10\x03\x12\x17\n" +
	"\x13POWER_MODE_BALANCED\x10\x042\xae\x01\n" +
	"\fPowerService\x12L\n" +
	"\x06Reboot\x12\x1e.api.gravity.v26.RebootRequest\x1a\".api.gravity.types.BooleanResponse\x12P\n" +
	"\bShutdown\x12 .api.gravity.v26.ShutdownRequest\x1a\".api.gravity.types.BooleanResponseb\x06proto3"

var (
	file_power_service_v26_power_service_proto_rawDescOnce sync.Once
	file_power_service_v26_power_service_proto_rawDescData []byte
)

func file_power_service_v26_power_service_proto_rawDescGZIP() []byte {
	file_power_service_v26_power_service_proto_rawDescOnce.Do(func() {
		file_power_service_v26_power_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_power_service_v26_power_service_proto_rawDesc), len(file_power_service_v26_power_service_proto_rawDesc)))
	})
	return file_power_service_v26_power_service_proto_rawDescData
}

var file_power_service_v26_power_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_power_service_v26_power_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_power_service_v26_power_service_proto_goTypes = []any{
	(PowerMode)(0),                 // 0: api.gravity.v26.PowerMode
	(*RebootRequest)(nil),          // 1: api.gravity.v26.RebootRequest
	(*ShutdownRequest)(nil),        // 2: api.gravity.v26.ShutdownRequest
	(*common.BooleanResponse)(nil), // 3: api.gravity.types.BooleanResponse
}
var file_power_service_v26_power_service_proto_depIdxs = []int32{
	1, // 0: api.gravity.v26.PowerService.Reboot:input_type -> api.gravity.v26.RebootRequest
	2, // 1: api.gravity.v26.PowerService.Shutdown:input_type -> api.gravity.v26.ShutdownRequest
	3, // 2: api.gravity.v26.PowerService.Reboot:output_type -> api.gravity.types.BooleanResponse
	3, // 3: api.gravity.v26.PowerService.Shutdown:output_type -> api.gravity.types.BooleanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_power_service_v26_power_service_proto_init() }
func file_power_service_v26_power_service_proto_init() {
	if File_power_service_v26_power_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_power_service_v26_power_service_proto_rawDesc), len(file_power_service_v26_power_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_power_service_v26_power_service_proto_goTypes,
		DependencyIndexes: file_power_service_v26_power_service_proto_depIdxs,
		EnumInfos:         file_power_service_v26_power_service_proto_enumTypes,
		MessageInfos:      file_power_service_v26_power_service_proto_msgTypes,
	}.Build()
	File_power_service_v26_power_service_proto = out.File
	file_power_service_v26_power_service_proto_goTypes = nil
	file_power_service_v26_power_service_proto_depIdxs = nil
}
