// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: package_service/v26/packagemanager_service.proto

package v26

import (
	context "context"
	common "github.com/OrbitOS-org/orbit-os-sdk-go/v26/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PackageManagerService_GetInstalledPackages_FullMethodName = "/api.gravity.v26.PackageManagerService/GetInstalledPackages"
	PackageManagerService_InstallUpdatePackage_FullMethodName = "/api.gravity.v26.PackageManagerService/InstallUpdatePackage"
	PackageManagerService_RemovePackage_FullMethodName        = "/api.gravity.v26.PackageManagerService/RemovePackage"
)

// PackageManagerServiceClient is the client API for PackageManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackageManagerServiceClient interface {
	GetInstalledPackages(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*InstalledPackagesResponse, error)
	InstallUpdatePackage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PackageChunk, common.BooleanResponse], error)
	RemovePackage(ctx context.Context, in *RemovePackageRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error)
}

type packageManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageManagerServiceClient(cc grpc.ClientConnInterface) PackageManagerServiceClient {
	return &packageManagerServiceClient{cc}
}

func (c *packageManagerServiceClient) GetInstalledPackages(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*InstalledPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstalledPackagesResponse)
	err := c.cc.Invoke(ctx, PackageManagerService_GetInstalledPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageManagerServiceClient) InstallUpdatePackage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PackageChunk, common.BooleanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PackageManagerService_ServiceDesc.Streams[0], PackageManagerService_InstallUpdatePackage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageChunk, common.BooleanResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManagerService_InstallUpdatePackageClient = grpc.ClientStreamingClient[PackageChunk, common.BooleanResponse]

func (c *packageManagerServiceClient) RemovePackage(ctx context.Context, in *RemovePackageRequest, opts ...grpc.CallOption) (*common.BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BooleanResponse)
	err := c.cc.Invoke(ctx, PackageManagerService_RemovePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackageManagerServiceServer is the server API for PackageManagerService service.
// All implementations must embed UnimplementedPackageManagerServiceServer
// for forward compatibility.
type PackageManagerServiceServer interface {
	GetInstalledPackages(context.Context, *common.Empty) (*InstalledPackagesResponse, error)
	InstallUpdatePackage(grpc.ClientStreamingServer[PackageChunk, common.BooleanResponse]) error
	RemovePackage(context.Context, *RemovePackageRequest) (*common.BooleanResponse, error)
	mustEmbedUnimplementedPackageManagerServiceServer()
}

// UnimplementedPackageManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackageManagerServiceServer struct{}

func (UnimplementedPackageManagerServiceServer) GetInstalledPackages(context.Context, *common.Empty) (*InstalledPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstalledPackages not implemented")
}
func (UnimplementedPackageManagerServiceServer) InstallUpdatePackage(grpc.ClientStreamingServer[PackageChunk, common.BooleanResponse]) error {
	return status.Error(codes.Unimplemented, "method InstallUpdatePackage not implemented")
}
func (UnimplementedPackageManagerServiceServer) RemovePackage(context.Context, *RemovePackageRequest) (*common.BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePackage not implemented")
}
func (UnimplementedPackageManagerServiceServer) mustEmbedUnimplementedPackageManagerServiceServer() {}
func (UnimplementedPackageManagerServiceServer) testEmbeddedByValue()                               {}

// UnsafePackageManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageManagerServiceServer will
// result in compilation errors.
type UnsafePackageManagerServiceServer interface {
	mustEmbedUnimplementedPackageManagerServiceServer()
}

func RegisterPackageManagerServiceServer(s grpc.ServiceRegistrar, srv PackageManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedPackageManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackageManagerService_ServiceDesc, srv)
}

func _PackageManagerService_GetInstalledPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServiceServer).GetInstalledPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManagerService_GetInstalledPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServiceServer).GetInstalledPackages(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageManagerService_InstallUpdatePackage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PackageManagerServiceServer).InstallUpdatePackage(&grpc.GenericServerStream[PackageChunk, common.BooleanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PackageManagerService_InstallUpdatePackageServer = grpc.ClientStreamingServer[PackageChunk, common.BooleanResponse]

func _PackageManagerService_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageManagerServiceServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackageManagerService_RemovePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageManagerServiceServer).RemovePackage(ctx, req.(*RemovePackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PackageManagerService_ServiceDesc is the grpc.ServiceDesc for PackageManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gravity.v26.PackageManagerService",
	HandlerType: (*PackageManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstalledPackages",
			Handler:    _PackageManagerService_GetInstalledPackages_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _PackageManagerService_RemovePackage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallUpdatePackage",
			Handler:       _PackageManagerService_InstallUpdatePackage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "package_service/v26/packagemanager_service.proto",
}
